var sceneWidth = 2304;

module.exports = {
    "name": "Krabi",
    "lat": 98.4334108,
    "lon": 8.0404036,
    "sceneWidth": sceneWidth,
    "sceneHeight": 1440,
    "objects": [
        {
            "id": "background",
            "image": "img/krabi/Krabi_Back.jpg",
            "position": [0, 0]
        },
        // {
        //     "id": "boat1",
        //     "image": "img/krabi/Boats.json",
        //     "frames": ["img/krabi/Boats_1.png"],
        //     "position": [379, 1032]
        // },
        // {
        //     "id": "boat2",
        //     "image": "img/krabi/Boats.json",
        //     "frames": ["img/krabi/Boats_2.png"],
        //     "position": [430, 1078]
        // },
        {
            "id": "boat3",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_3.png"],
            "position": [518, 281]
        },
        {
            "id": "boat4",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_4.png"],
            "position": [644, 404]
        },
        {
            "id": "boat6",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_6.png"],
            "position": [687, 309]
        },
        {
            "id": "boat7",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_7.png"],
            "position": [722, 1186]
        },
        {
            "id": "boat8",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_8.png"],
            "position": [744, 491]
        },
        {
            "id": "boat9",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_9.png"],
            "position": [779, 610]
        },
        // {
        //     "id": "boat10",
        //     "image": "img/krabi/Boats.json",
        //     "frames": ["img/krabi/Boats_10.png"],
        //     "position": [819, 819]
        // },
        {
            "id": "boat11",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_11.png"],
            "position": [854, 1233]
        },
        // {
        //     "id": "boat15",
        //     "image": "img/krabi/Boats.json",
        //     "frames": ["img/krabi/Boats_15.png"],
        //     "position": [926, 950]
        // },
        {
            "id": "boat16",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_16.png"],
            "position": [1016, 1144]
        },
        {
            "id": "boat17",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_17.png"],
            "position": [1071, 582]
        },
        {
            "id": "boat18",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_18.png"],
            "position": [1151, 440]
        },
        // {
        //     "id": "boat20",
        //     "image": "img/krabi/Boats.json",
        //     "frames": ["img/krabi/Boats_20.png"],
        //     "position": [1301, 792]
        // },
        {
            "id": "boat21",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_21.png"],
            "position": [1319, 514]
        },
        {
            "id": "boat23",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_23.png"],
            "position": [1435, 709]
        },
        {
            "id": "boat24",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_24.png"],
            "position": [1441, 348]
        },
        {
            "id": "boat26",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_26.png"],
            "position": [1560, 1072]
        },
        {
            "id": "boat27",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_27.png"],
            "position": [1591, 313]
        },
        {
            "id": "boat28",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_28.png"],
            "position": [1611, 783]
        },
        {
            "id": "boat30",
            "image": "img/krabi/Boats.json",
            "frames": ["img/krabi/Boats_30.png"],
            "position": [1992, 271]
        },
        {
            "id": "movingBoat1",
            "image": "img/krabi/movingBoat1.json",
            "frames": [
                "img/krabi/movingBoat1/movingBoat1_00.png",
                "img/krabi/movingBoat1/movingBoat1_01.png",
                "img/krabi/movingBoat1/movingBoat1_02.png",
                "img/krabi/movingBoat1/movingBoat1_03.png",
                "img/krabi/movingBoat1/movingBoat1_04.png",
                "img/krabi/movingBoat1/movingBoat1_05.png",
                "img/krabi/movingBoat1/movingBoat1_06.png",
                "img/krabi/movingBoat1/movingBoat1_07.png",
                "img/krabi/movingBoat1/movingBoat1_08.png",
                "img/krabi/movingBoat1/movingBoat1_09.png",
                "img/krabi/movingBoat1/movingBoat1_10.png",
                "img/krabi/movingBoat1/movingBoat1_11.png",
                "img/krabi/movingBoat1/movingBoat1_12.png",
                "img/krabi/movingBoat1/movingBoat1_13.png",
                "img/krabi/movingBoat1/movingBoat1_14.png",
                "img/krabi/movingBoat1/movingBoat1_15.png",
                "img/krabi/movingBoat1/movingBoat1_16.png",
                "img/krabi/movingBoat1/movingBoat1_17.png",
                "img/krabi/movingBoat1/movingBoat1_18.png",
                "img/krabi/movingBoat1/movingBoat1_19.png",
                "img/krabi/movingBoat1/movingBoat1_20.png",
                "img/krabi/movingBoat1/movingBoat1_21.png",
                "img/krabi/movingBoat1/movingBoat1_22.png",
                "img/krabi/movingBoat1/movingBoat1_23.png",
                "img/krabi/movingBoat1/movingBoat1_24.png",
                "img/krabi/movingBoat1/movingBoat1_25.png",
                "img/krabi/movingBoat1/movingBoat1_26.png",
                "img/krabi/movingBoat1/movingBoat1_27.png",
                "img/krabi/movingBoat1/movingBoat1_28.png",
                "img/krabi/movingBoat1/movingBoat1_29.png",
                "img/krabi/movingBoat1/movingBoat1_30.png",
                "img/krabi/movingBoat1/movingBoat1_31.png",
                "img/krabi/movingBoat1/movingBoat1_32.png",
                "img/krabi/movingBoat1/movingBoat1_33.png",
                "img/krabi/movingBoat1/movingBoat1_34.png",
                "img/krabi/movingBoat1/movingBoat1_35.png",
                "img/krabi/movingBoat1/movingBoat1_36.png",
                "img/krabi/movingBoat1/movingBoat1_37.png",
                "img/krabi/movingBoat1/movingBoat1_38.png",
                "img/krabi/movingBoat1/movingBoat1_39.png",
                "img/krabi/movingBoat1/movingBoat1_40.png",
                "img/krabi/movingBoat1/movingBoat1_41.png",
                "img/krabi/movingBoat1/movingBoat1_42.png",
                "img/krabi/movingBoat1/movingBoat1_43.png",
                "img/krabi/movingBoat1/movingBoat1_44.png",
                "img/krabi/movingBoat1/movingBoat1_45.png",
                "img/krabi/movingBoat1/movingBoat1_46.png",
                "img/krabi/movingBoat1/movingBoat1_47.png",
                "img/krabi/movingBoat1/movingBoat1_48.png",
                "img/krabi/movingBoat1/movingBoat1_49.png",
                "img/krabi/movingBoat1/movingBoat1_50.png",
                "img/krabi/movingBoat1/movingBoat1_51.png",
                "img/krabi/movingBoat1/movingBoat1_52.png",
                "img/krabi/movingBoat1/movingBoat1_53.png",
                "img/krabi/movingBoat1/movingBoat1_54.png",
                "img/krabi/movingBoat1/movingBoat1_55.png",
                "img/krabi/movingBoat1/movingBoat1_56.png",
                "img/krabi/movingBoat1/movingBoat1_57.png",
                "img/krabi/movingBoat1/movingBoat1_58.png",
                "img/krabi/movingBoat1/movingBoat1_59.png",
                "img/krabi/movingBoat1/movingBoat1_60.png",
                "img/krabi/movingBoat1/movingBoat1_61.png",
                "img/krabi/movingBoat1/movingBoat1_62.png",
                "img/krabi/movingBoat1/movingBoat1_63.png",
                "img/krabi/movingBoat1/movingBoat1_64.png",
                "img/krabi/movingBoat1/movingBoat1_65.png",
                "img/krabi/movingBoat1/movingBoat1_66.png",
                "img/krabi/movingBoat1/movingBoat1_67.png",
                "img/krabi/movingBoat1/movingBoat1_68.png",
                "img/krabi/movingBoat1/movingBoat1_69.png",
                "img/krabi/movingBoat1/movingBoat1_70.png",
                "img/krabi/movingBoat1/movingBoat1_71.png",
                "img/krabi/movingBoat1/movingBoat1_72.png",
                "img/krabi/movingBoat1/movingBoat1_73.png",
                "img/krabi/movingBoat1/movingBoat1_74.png",
                "img/krabi/movingBoat1/movingBoat1_75.png",
                "img/krabi/movingBoat1/movingBoat1_76.png",
                "img/krabi/movingBoat1/movingBoat1_77.png",
                "img/krabi/movingBoat1/movingBoat1_78.png",
                "img/krabi/movingBoat1/movingBoat1_79.png",
                "img/krabi/movingBoat1/movingBoat1_80.png",
                "img/krabi/movingBoat1/movingBoat1_81.png",
                "img/krabi/movingBoat1/movingBoat1_82.png",
                "img/krabi/movingBoat1/movingBoat1_83.png",
                "img/krabi/movingBoat1/movingBoat1_84.png",
                "img/krabi/movingBoat1/movingBoat1_85.png",
                "img/krabi/movingBoat1/movingBoat1_86.png",
                "img/krabi/movingBoat1/movingBoat1_87.png",
                "img/krabi/movingBoat1/movingBoat1_88.png",
                "img/krabi/movingBoat1/movingBoat1_89.png",
                "img/krabi/movingBoat1/movingBoat1_90.png",
                "img/krabi/movingBoat1/movingBoat1_91.png",
                "img/krabi/movingBoat1/movingBoat1_92.png",
                "img/krabi/movingBoat1/movingBoat1_93.png",
                "img/krabi/movingBoat1/movingBoat1_94.png",
                "img/krabi/movingBoat1/movingBoat1_95.png",
                "img/krabi/movingBoat1/movingBoat1_96.png"
            ]
        },
        {
            "id": "movingBoat2",
            "image": "img/krabi/movingBoat2.json",
            "frames": [
                "img/krabi/movingBoat2/movingBoat2_00.png",
                "img/krabi/movingBoat2/movingBoat2_01.png",
                "img/krabi/movingBoat2/movingBoat2_02.png",
                "img/krabi/movingBoat2/movingBoat2_03.png",
                "img/krabi/movingBoat2/movingBoat2_04.png",
                "img/krabi/movingBoat2/movingBoat2_05.png",
                "img/krabi/movingBoat2/movingBoat2_06.png",
                "img/krabi/movingBoat2/movingBoat2_07.png",
                "img/krabi/movingBoat2/movingBoat2_08.png",
                "img/krabi/movingBoat2/movingBoat2_09.png",
                "img/krabi/movingBoat2/movingBoat2_10.png",
                "img/krabi/movingBoat2/movingBoat2_11.png",
                "img/krabi/movingBoat2/movingBoat2_12.png",
                "img/krabi/movingBoat2/movingBoat2_13.png",
                "img/krabi/movingBoat2/movingBoat2_14.png",
                "img/krabi/movingBoat2/movingBoat2_15.png",
                "img/krabi/movingBoat2/movingBoat2_16.png",
                "img/krabi/movingBoat2/movingBoat2_17.png",
                "img/krabi/movingBoat2/movingBoat2_18.png",
                "img/krabi/movingBoat2/movingBoat2_19.png",
                "img/krabi/movingBoat2/movingBoat2_20.png",
                "img/krabi/movingBoat2/movingBoat2_21.png",
                "img/krabi/movingBoat2/movingBoat2_22.png",
                "img/krabi/movingBoat2/movingBoat2_23.png",
                "img/krabi/movingBoat2/movingBoat2_24.png",
                "img/krabi/movingBoat2/movingBoat2_25.png",
                "img/krabi/movingBoat2/movingBoat2_26.png",
                "img/krabi/movingBoat2/movingBoat2_27.png",
                "img/krabi/movingBoat2/movingBoat2_28.png",
                "img/krabi/movingBoat2/movingBoat2_29.png",
                "img/krabi/movingBoat2/movingBoat2_30.png",
                "img/krabi/movingBoat2/movingBoat2_31.png",
                "img/krabi/movingBoat2/movingBoat2_32.png",
                "img/krabi/movingBoat2/movingBoat2_33.png",
                "img/krabi/movingBoat2/movingBoat2_34.png",
                "img/krabi/movingBoat2/movingBoat2_35.png",
                "img/krabi/movingBoat2/movingBoat2_36.png",
                "img/krabi/movingBoat2/movingBoat2_37.png",
                "img/krabi/movingBoat2/movingBoat2_38.png",
                "img/krabi/movingBoat2/movingBoat2_39.png",
                "img/krabi/movingBoat2/movingBoat2_40.png",
                "img/krabi/movingBoat2/movingBoat2_41.png",
                "img/krabi/movingBoat2/movingBoat2_42.png",
                "img/krabi/movingBoat2/movingBoat2_43.png",
                "img/krabi/movingBoat2/movingBoat2_44.png",
                "img/krabi/movingBoat2/movingBoat2_45.png",
                "img/krabi/movingBoat2/movingBoat2_46.png",
                "img/krabi/movingBoat2/movingBoat2_47.png",
                "img/krabi/movingBoat2/movingBoat2_48.png",
                "img/krabi/movingBoat2/movingBoat2_49.png",
                "img/krabi/movingBoat2/movingBoat2_50.png",
                "img/krabi/movingBoat2/movingBoat2_51.png",
                "img/krabi/movingBoat2/movingBoat2_52.png",
                "img/krabi/movingBoat2/movingBoat2_53.png",
                "img/krabi/movingBoat2/movingBoat2_54.png",
                "img/krabi/movingBoat2/movingBoat2_55.png",
                "img/krabi/movingBoat2/movingBoat2_56.png",
                "img/krabi/movingBoat2/movingBoat2_57.png",
                "img/krabi/movingBoat2/movingBoat2_58.png",
                "img/krabi/movingBoat2/movingBoat2_59.png",
                "img/krabi/movingBoat2/movingBoat2_60.png",
                "img/krabi/movingBoat2/movingBoat2_61.png",
                "img/krabi/movingBoat2/movingBoat2_62.png",
                "img/krabi/movingBoat2/movingBoat2_63.png",
                "img/krabi/movingBoat2/movingBoat2_64.png",
                "img/krabi/movingBoat2/movingBoat2_65.png",
                "img/krabi/movingBoat2/movingBoat2_66.png",
                "img/krabi/movingBoat2/movingBoat2_67.png",
                "img/krabi/movingBoat2/movingBoat2_68.png",
                "img/krabi/movingBoat2/movingBoat2_69.png",
                "img/krabi/movingBoat2/movingBoat2_70.png",
                "img/krabi/movingBoat2/movingBoat2_71.png",
                "img/krabi/movingBoat2/movingBoat2_72.png",
                "img/krabi/movingBoat2/movingBoat2_73.png",
                "img/krabi/movingBoat2/movingBoat2_74.png",
                "img/krabi/movingBoat2/movingBoat2_75.png",
                "img/krabi/movingBoat2/movingBoat2_76.png",
                "img/krabi/movingBoat2/movingBoat2_77.png",
                "img/krabi/movingBoat2/movingBoat2_78.png",
                "img/krabi/movingBoat2/movingBoat2_79.png",
                "img/krabi/movingBoat2/movingBoat2_80.png",
                "img/krabi/movingBoat2/movingBoat2_81.png",
                "img/krabi/movingBoat2/movingBoat2_82.png",
                "img/krabi/movingBoat2/movingBoat2_83.png",
                "img/krabi/movingBoat2/movingBoat2_84.png",
                "img/krabi/movingBoat2/movingBoat2_85.png",
                "img/krabi/movingBoat2/movingBoat2_86.png",
                "img/krabi/movingBoat2/movingBoat2_87.png",
                "img/krabi/movingBoat2/movingBoat2_88.png",
                "img/krabi/movingBoat2/movingBoat2_89.png",
                "img/krabi/movingBoat2/movingBoat2_90.png",
                "img/krabi/movingBoat2/movingBoat2_91.png",
                "img/krabi/movingBoat2/movingBoat2_92.png",
                "img/krabi/movingBoat2/movingBoat2_93.png",
                "img/krabi/movingBoat2/movingBoat2_94.png",
                "img/krabi/movingBoat2/movingBoat2_95.png",
                "img/krabi/movingBoat2/movingBoat2_96.png"
            ]
        },
        {
            "id": "movingBoat3",
            "image": "img/krabi/movingBoat3.json",
            "frames": [
                "img/krabi/movingBoat3/movingBoat3_00.png",
                "img/krabi/movingBoat3/movingBoat3_01.png",
                "img/krabi/movingBoat3/movingBoat3_02.png",
                "img/krabi/movingBoat3/movingBoat3_03.png",
                "img/krabi/movingBoat3/movingBoat3_04.png",
                "img/krabi/movingBoat3/movingBoat3_05.png",
                "img/krabi/movingBoat3/movingBoat3_06.png",
                "img/krabi/movingBoat3/movingBoat3_07.png",
                "img/krabi/movingBoat3/movingBoat3_08.png",
                "img/krabi/movingBoat3/movingBoat3_09.png",
                "img/krabi/movingBoat3/movingBoat3_10.png",
                "img/krabi/movingBoat3/movingBoat3_11.png",
                "img/krabi/movingBoat3/movingBoat3_12.png",
                "img/krabi/movingBoat3/movingBoat3_13.png",
                "img/krabi/movingBoat3/movingBoat3_14.png",
                "img/krabi/movingBoat3/movingBoat3_15.png",
                "img/krabi/movingBoat3/movingBoat3_16.png",
                "img/krabi/movingBoat3/movingBoat3_17.png",
                "img/krabi/movingBoat3/movingBoat3_18.png",
                "img/krabi/movingBoat3/movingBoat3_19.png",
                "img/krabi/movingBoat3/movingBoat3_20.png",
                "img/krabi/movingBoat3/movingBoat3_21.png",
                "img/krabi/movingBoat3/movingBoat3_22.png",
                "img/krabi/movingBoat3/movingBoat3_23.png",
                "img/krabi/movingBoat3/movingBoat3_24.png",
                "img/krabi/movingBoat3/movingBoat3_25.png",
                "img/krabi/movingBoat3/movingBoat3_26.png",
                "img/krabi/movingBoat3/movingBoat3_27.png",
                "img/krabi/movingBoat3/movingBoat3_28.png",
                "img/krabi/movingBoat3/movingBoat3_29.png",
                "img/krabi/movingBoat3/movingBoat3_30.png",
                "img/krabi/movingBoat3/movingBoat3_31.png",
                "img/krabi/movingBoat3/movingBoat3_32.png",
                "img/krabi/movingBoat3/movingBoat3_33.png",
                "img/krabi/movingBoat3/movingBoat3_34.png",
                "img/krabi/movingBoat3/movingBoat3_35.png",
                "img/krabi/movingBoat3/movingBoat3_36.png",
                "img/krabi/movingBoat3/movingBoat3_37.png",
                "img/krabi/movingBoat3/movingBoat3_38.png",
                "img/krabi/movingBoat3/movingBoat3_39.png",
                "img/krabi/movingBoat3/movingBoat3_40.png",
                "img/krabi/movingBoat3/movingBoat3_41.png",
                "img/krabi/movingBoat3/movingBoat3_42.png",
                "img/krabi/movingBoat3/movingBoat3_43.png",
                "img/krabi/movingBoat3/movingBoat3_44.png",
                "img/krabi/movingBoat3/movingBoat3_45.png",
                "img/krabi/movingBoat3/movingBoat3_46.png",
                "img/krabi/movingBoat3/movingBoat3_47.png",
                "img/krabi/movingBoat3/movingBoat3_48.png",
                "img/krabi/movingBoat3/movingBoat3_49.png",
                "img/krabi/movingBoat3/movingBoat3_50.png",
                "img/krabi/movingBoat3/movingBoat3_51.png",
                "img/krabi/movingBoat3/movingBoat3_52.png",
                "img/krabi/movingBoat3/movingBoat3_53.png",
                "img/krabi/movingBoat3/movingBoat3_54.png",
                "img/krabi/movingBoat3/movingBoat3_55.png",
                "img/krabi/movingBoat3/movingBoat3_56.png",
                "img/krabi/movingBoat3/movingBoat3_57.png",
                "img/krabi/movingBoat3/movingBoat3_58.png",
                "img/krabi/movingBoat3/movingBoat3_59.png",
                "img/krabi/movingBoat3/movingBoat3_60.png",
                "img/krabi/movingBoat3/movingBoat3_61.png",
                "img/krabi/movingBoat3/movingBoat3_62.png",
                "img/krabi/movingBoat3/movingBoat3_63.png",
                "img/krabi/movingBoat3/movingBoat3_64.png",
                "img/krabi/movingBoat3/movingBoat3_65.png",
                "img/krabi/movingBoat3/movingBoat3_66.png",
                "img/krabi/movingBoat3/movingBoat3_67.png",
                "img/krabi/movingBoat3/movingBoat3_68.png",
                "img/krabi/movingBoat3/movingBoat3_69.png",
                "img/krabi/movingBoat3/movingBoat3_70.png",
                "img/krabi/movingBoat3/movingBoat3_71.png",
                "img/krabi/movingBoat3/movingBoat3_72.png",
                "img/krabi/movingBoat3/movingBoat3_73.png",
                "img/krabi/movingBoat3/movingBoat3_74.png",
                "img/krabi/movingBoat3/movingBoat3_75.png",
                "img/krabi/movingBoat3/movingBoat3_76.png",
                "img/krabi/movingBoat3/movingBoat3_77.png",
                "img/krabi/movingBoat3/movingBoat3_78.png",
                "img/krabi/movingBoat3/movingBoat3_79.png",
                "img/krabi/movingBoat3/movingBoat3_80.png",
                "img/krabi/movingBoat3/movingBoat3_81.png",
                "img/krabi/movingBoat3/movingBoat3_82.png",
                "img/krabi/movingBoat3/movingBoat3_83.png",
                "img/krabi/movingBoat3/movingBoat3_84.png",
                "img/krabi/movingBoat3/movingBoat3_85.png",
                "img/krabi/movingBoat3/movingBoat3_86.png",
                "img/krabi/movingBoat3/movingBoat3_87.png",
                "img/krabi/movingBoat3/movingBoat3_88.png",
                "img/krabi/movingBoat3/movingBoat3_89.png",
                "img/krabi/movingBoat3/movingBoat3_90.png",
                "img/krabi/movingBoat3/movingBoat3_91.png",
                "img/krabi/movingBoat3/movingBoat3_92.png",
                "img/krabi/movingBoat3/movingBoat3_93.png",
                "img/krabi/movingBoat3/movingBoat3_94.png",
                "img/krabi/movingBoat3/movingBoat3_95.png",
                "img/krabi/movingBoat3/movingBoat3_96.png"
            ]
        },
        {
            "id": "movingBoat4",
            "image": "img/krabi/movingBoat4.json",
            "frames": [
                "img/krabi/movingBoat4/movingBoat4_00.png",
                "img/krabi/movingBoat4/movingBoat4_01.png",
                "img/krabi/movingBoat4/movingBoat4_02.png",
                "img/krabi/movingBoat4/movingBoat4_03.png",
                "img/krabi/movingBoat4/movingBoat4_04.png",
                "img/krabi/movingBoat4/movingBoat4_05.png",
                "img/krabi/movingBoat4/movingBoat4_06.png",
                "img/krabi/movingBoat4/movingBoat4_07.png",
                "img/krabi/movingBoat4/movingBoat4_08.png",
                "img/krabi/movingBoat4/movingBoat4_09.png",
                "img/krabi/movingBoat4/movingBoat4_10.png",
                "img/krabi/movingBoat4/movingBoat4_11.png",
                "img/krabi/movingBoat4/movingBoat4_12.png",
                "img/krabi/movingBoat4/movingBoat4_13.png",
                "img/krabi/movingBoat4/movingBoat4_14.png",
                "img/krabi/movingBoat4/movingBoat4_15.png",
                "img/krabi/movingBoat4/movingBoat4_16.png",
                "img/krabi/movingBoat4/movingBoat4_17.png",
                "img/krabi/movingBoat4/movingBoat4_18.png",
                "img/krabi/movingBoat4/movingBoat4_19.png",
                "img/krabi/movingBoat4/movingBoat4_20.png",
                "img/krabi/movingBoat4/movingBoat4_21.png",
                "img/krabi/movingBoat4/movingBoat4_22.png",
                "img/krabi/movingBoat4/movingBoat4_23.png",
                "img/krabi/movingBoat4/movingBoat4_24.png",
                "img/krabi/movingBoat4/movingBoat4_25.png",
                "img/krabi/movingBoat4/movingBoat4_26.png",
                "img/krabi/movingBoat4/movingBoat4_27.png",
                "img/krabi/movingBoat4/movingBoat4_28.png",
                "img/krabi/movingBoat4/movingBoat4_29.png",
                "img/krabi/movingBoat4/movingBoat4_30.png",
                "img/krabi/movingBoat4/movingBoat4_31.png",
                "img/krabi/movingBoat4/movingBoat4_32.png",
                "img/krabi/movingBoat4/movingBoat4_33.png",
                "img/krabi/movingBoat4/movingBoat4_34.png",
                "img/krabi/movingBoat4/movingBoat4_35.png",
                "img/krabi/movingBoat4/movingBoat4_36.png",
                "img/krabi/movingBoat4/movingBoat4_37.png",
                "img/krabi/movingBoat4/movingBoat4_38.png",
                "img/krabi/movingBoat4/movingBoat4_39.png",
                "img/krabi/movingBoat4/movingBoat4_40.png",
                "img/krabi/movingBoat4/movingBoat4_41.png",
                "img/krabi/movingBoat4/movingBoat4_42.png",
                "img/krabi/movingBoat4/movingBoat4_43.png",
                "img/krabi/movingBoat4/movingBoat4_44.png",
                "img/krabi/movingBoat4/movingBoat4_45.png",
                "img/krabi/movingBoat4/movingBoat4_46.png",
                "img/krabi/movingBoat4/movingBoat4_47.png",
                "img/krabi/movingBoat4/movingBoat4_48.png",
                "img/krabi/movingBoat4/movingBoat4_49.png",
                "img/krabi/movingBoat4/movingBoat4_50.png",
                "img/krabi/movingBoat4/movingBoat4_51.png",
                "img/krabi/movingBoat4/movingBoat4_52.png",
                "img/krabi/movingBoat4/movingBoat4_53.png",
                "img/krabi/movingBoat4/movingBoat4_54.png",
                "img/krabi/movingBoat4/movingBoat4_55.png",
                "img/krabi/movingBoat4/movingBoat4_56.png",
                "img/krabi/movingBoat4/movingBoat4_57.png",
                "img/krabi/movingBoat4/movingBoat4_58.png",
                "img/krabi/movingBoat4/movingBoat4_59.png",
                "img/krabi/movingBoat4/movingBoat4_60.png",
                "img/krabi/movingBoat4/movingBoat4_61.png",
                "img/krabi/movingBoat4/movingBoat4_62.png",
                "img/krabi/movingBoat4/movingBoat4_63.png",
                "img/krabi/movingBoat4/movingBoat4_64.png",
                "img/krabi/movingBoat4/movingBoat4_65.png",
                "img/krabi/movingBoat4/movingBoat4_66.png",
                "img/krabi/movingBoat4/movingBoat4_67.png",
                "img/krabi/movingBoat4/movingBoat4_68.png",
                "img/krabi/movingBoat4/movingBoat4_69.png",
                "img/krabi/movingBoat4/movingBoat4_70.png",
                "img/krabi/movingBoat4/movingBoat4_71.png",
                "img/krabi/movingBoat4/movingBoat4_72.png",
                "img/krabi/movingBoat4/movingBoat4_73.png",
                "img/krabi/movingBoat4/movingBoat4_74.png",
                "img/krabi/movingBoat4/movingBoat4_75.png",
                "img/krabi/movingBoat4/movingBoat4_76.png",
                "img/krabi/movingBoat4/movingBoat4_77.png",
                "img/krabi/movingBoat4/movingBoat4_78.png",
                "img/krabi/movingBoat4/movingBoat4_79.png",
                "img/krabi/movingBoat4/movingBoat4_80.png",
                "img/krabi/movingBoat4/movingBoat4_81.png",
                "img/krabi/movingBoat4/movingBoat4_82.png",
                "img/krabi/movingBoat4/movingBoat4_83.png",
                "img/krabi/movingBoat4/movingBoat4_84.png",
                "img/krabi/movingBoat4/movingBoat4_85.png",
                "img/krabi/movingBoat4/movingBoat4_86.png",
                "img/krabi/movingBoat4/movingBoat4_87.png",
                "img/krabi/movingBoat4/movingBoat4_88.png",
                "img/krabi/movingBoat4/movingBoat4_89.png",
                "img/krabi/movingBoat4/movingBoat4_90.png",
                "img/krabi/movingBoat4/movingBoat4_91.png",
                "img/krabi/movingBoat4/movingBoat4_92.png",
                "img/krabi/movingBoat4/movingBoat4_93.png",
                "img/krabi/movingBoat4/movingBoat4_94.png",
                "img/krabi/movingBoat4/movingBoat4_95.png",
                "img/krabi/movingBoat4/movingBoat4_96.png"
            ]
        },
        {
            "id": "bird1",
            "image": "img/krabi/Seagull1.json",
            "frames": [
                "img/krabi/Krabi_Gull1/Krabi_Gull1_00.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_01.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_02.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_03.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_04.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_05.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_06.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_07.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_08.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_09.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_10.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_11.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_12.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_13.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_14.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_15.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_16.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_17.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_18.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_19.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_20.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_21.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_22.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_23.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_24.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_25.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_26.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_27.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_28.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_29.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_30.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_31.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_32.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_33.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_34.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_35.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_36.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_37.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_38.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_39.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_40.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_41.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_42.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_43.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_44.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_45.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_46.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_47.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_48.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_49.png"
            ],
            "position": [85, 273]
        },
        {
            "id": "bird2",
            "image": "img/krabi/Seagull1.json",
            "frames": [
                "img/krabi/Krabi_Gull1/Krabi_Gull1_00.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_01.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_02.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_03.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_04.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_05.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_06.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_07.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_08.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_09.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_10.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_11.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_12.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_13.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_14.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_15.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_16.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_17.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_18.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_19.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_20.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_21.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_22.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_23.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_24.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_25.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_26.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_27.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_28.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_29.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_30.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_31.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_32.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_33.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_34.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_35.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_36.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_37.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_38.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_39.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_40.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_41.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_42.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_43.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_44.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_45.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_46.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_47.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_48.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_49.png"
            ],
            "position": [296, 81]
        },
        {
            "id": "bird3",
            "image": "img/krabi/Seagull1.json",
            "frames": [
                "img/krabi/Krabi_Gull1/Krabi_Gull1_00.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_01.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_02.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_03.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_04.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_05.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_06.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_07.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_08.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_09.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_10.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_11.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_12.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_13.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_14.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_15.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_16.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_17.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_18.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_19.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_20.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_21.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_22.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_23.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_24.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_25.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_26.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_27.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_28.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_29.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_30.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_31.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_32.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_33.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_34.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_35.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_36.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_37.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_38.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_39.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_40.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_41.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_42.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_43.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_44.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_45.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_46.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_47.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_48.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_49.png"
            ],
            "position": [368, 72]
        },
        {
            "id": "bird4",
            "image": "img/krabi/Seagull1.json",
            "frames": [
                "img/krabi/Krabi_Gull1/Krabi_Gull1_00.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_01.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_02.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_03.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_04.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_05.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_06.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_07.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_08.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_09.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_10.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_11.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_12.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_13.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_14.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_15.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_16.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_17.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_18.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_19.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_20.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_21.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_22.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_23.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_24.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_25.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_26.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_27.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_28.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_29.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_30.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_31.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_32.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_33.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_34.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_35.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_36.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_37.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_38.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_39.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_40.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_41.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_42.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_43.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_44.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_45.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_46.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_47.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_48.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_49.png"
            ],
            "position": [375, 414]
        },
        {
            "id": "bird5",
            "image": "img/krabi/Seagull1.json",
            "frames": [
                "img/krabi/Krabi_Gull1/Krabi_Gull1_00.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_01.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_02.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_03.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_04.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_05.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_06.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_07.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_08.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_09.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_10.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_11.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_12.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_13.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_14.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_15.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_16.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_17.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_18.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_19.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_20.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_21.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_22.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_23.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_24.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_25.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_26.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_27.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_28.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_29.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_30.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_31.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_32.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_33.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_34.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_35.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_36.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_37.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_38.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_39.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_40.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_41.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_42.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_43.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_44.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_45.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_46.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_47.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_48.png",
                "img/krabi/Krabi_Gull1/Krabi_Gull1_49.png"
            ],
            "position": [527, 82]
        },
        {
            "id": "bird6",
            "image": "img/krabi/Seagull2.json",
            "frames": [
                "img/krabi/Krabi_Gull2/Krabi_Gull2_00.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_01.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_02.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_03.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_04.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_05.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_06.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_07.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_08.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_09.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_10.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_11.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_12.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_13.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_14.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_15.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_16.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_17.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_18.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_19.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_20.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_21.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_22.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_23.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_24.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_25.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_26.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_27.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_28.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_29.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_30.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_31.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_32.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_33.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_34.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_35.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_36.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_37.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_38.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_39.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_40.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_41.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_42.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_43.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_44.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_45.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_46.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_47.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_48.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_49.png"
            ],
            "position": [601, 255]
        },
        {
            "id": "bird7",
            "image": "img/krabi/Seagull2.json",
            "frames": [
                "img/krabi/Krabi_Gull2/Krabi_Gull2_00.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_01.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_02.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_03.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_04.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_05.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_06.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_07.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_08.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_09.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_10.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_11.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_12.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_13.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_14.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_15.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_16.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_17.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_18.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_19.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_20.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_21.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_22.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_23.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_24.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_25.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_26.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_27.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_28.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_29.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_30.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_31.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_32.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_33.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_34.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_35.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_36.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_37.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_38.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_39.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_40.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_41.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_42.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_43.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_44.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_45.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_46.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_47.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_48.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_49.png"
            ],
            "position": [684, 622]
        },
        {
            "id": "bird8",
            "image": "img/krabi/Seagull2.json",
            "frames": [
                "img/krabi/Krabi_Gull2/Krabi_Gull2_00.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_01.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_02.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_03.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_04.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_05.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_06.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_07.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_08.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_09.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_10.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_11.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_12.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_13.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_14.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_15.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_16.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_17.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_18.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_19.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_20.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_21.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_22.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_23.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_24.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_25.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_26.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_27.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_28.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_29.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_30.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_31.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_32.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_33.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_34.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_35.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_36.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_37.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_38.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_39.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_40.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_41.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_42.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_43.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_44.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_45.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_46.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_47.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_48.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_49.png"
            ],
            "position": [702, 573]
        },
        {
            "id": "bird9",
            "image": "img/krabi/Seagull2.json",
            "frames": [
                "img/krabi/Krabi_Gull2/Krabi_Gull2_00.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_01.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_02.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_03.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_04.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_05.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_06.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_07.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_08.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_09.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_10.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_11.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_12.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_13.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_14.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_15.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_16.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_17.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_18.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_19.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_20.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_21.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_22.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_23.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_24.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_25.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_26.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_27.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_28.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_29.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_30.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_31.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_32.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_33.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_34.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_35.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_36.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_37.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_38.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_39.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_40.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_41.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_42.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_43.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_44.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_45.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_46.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_47.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_48.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_49.png"
            ],
            "position": [841, 1141]
        },
        {
            "id": "bird10",
            "image": "img/krabi/Seagull2.json",
            "frames": [
                "img/krabi/Krabi_Gull2/Krabi_Gull2_00.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_01.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_02.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_03.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_04.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_05.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_06.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_07.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_08.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_09.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_10.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_11.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_12.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_13.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_14.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_15.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_16.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_17.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_18.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_19.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_20.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_21.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_22.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_23.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_24.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_25.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_26.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_27.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_28.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_29.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_30.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_31.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_32.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_33.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_34.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_35.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_36.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_37.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_38.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_39.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_40.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_41.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_42.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_43.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_44.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_45.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_46.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_47.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_48.png",
                "img/krabi/Krabi_Gull2/Krabi_Gull2_49.png"
            ],
            "position": [1395, 284]
        },
        {
            "id": "bird11",
            "image": "img/krabi/Seagull3.json",
            "frames": [
                "img/krabi/Krabi_Gull3/Krabi_Gull3_00.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_01.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_02.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_03.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_04.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_05.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_06.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_07.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_08.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_09.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_10.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_11.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_12.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_13.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_14.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_15.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_16.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_17.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_18.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_19.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_20.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_21.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_22.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_23.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_24.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_25.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_26.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_27.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_28.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_29.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_30.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_31.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_32.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_33.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_34.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_35.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_36.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_37.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_38.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_39.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_40.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_41.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_42.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_43.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_44.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_45.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_46.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_47.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_48.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_49.png"
            ],
            "position": [1535, 548]
        },
        {
            "id": "bird12",
            "image": "img/krabi/Seagull3.json",
            "frames": [
                "img/krabi/Krabi_Gull3/Krabi_Gull3_00.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_01.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_02.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_03.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_04.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_05.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_06.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_07.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_08.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_09.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_10.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_11.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_12.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_13.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_14.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_15.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_16.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_17.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_18.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_19.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_20.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_21.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_22.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_23.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_24.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_25.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_26.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_27.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_28.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_29.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_30.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_31.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_32.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_33.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_34.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_35.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_36.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_37.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_38.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_39.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_40.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_41.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_42.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_43.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_44.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_45.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_46.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_47.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_48.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_49.png"
            ],
            "position": [1612, 443]
        },
        {
            "id": "bird13",
            "image": "img/krabi/Seagull3.json",
            "frames": [
                "img/krabi/Krabi_Gull3/Krabi_Gull3_00.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_01.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_02.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_03.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_04.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_05.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_06.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_07.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_08.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_09.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_10.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_11.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_12.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_13.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_14.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_15.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_16.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_17.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_18.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_19.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_20.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_21.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_22.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_23.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_24.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_25.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_26.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_27.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_28.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_29.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_30.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_31.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_32.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_33.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_34.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_35.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_36.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_37.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_38.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_39.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_40.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_41.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_42.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_43.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_44.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_45.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_46.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_47.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_48.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_49.png"
            ],
            "position": [1747, 386]
        },
        {
            "id": "bird14",
            "image": "img/krabi/Seagull3.json",
            "frames": [
                "img/krabi/Krabi_Gull3/Krabi_Gull3_00.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_01.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_02.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_03.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_04.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_05.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_06.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_07.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_08.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_09.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_10.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_11.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_12.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_13.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_14.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_15.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_16.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_17.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_18.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_19.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_20.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_21.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_22.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_23.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_24.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_25.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_26.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_27.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_28.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_29.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_30.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_31.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_32.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_33.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_34.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_35.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_36.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_37.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_38.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_39.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_40.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_41.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_42.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_43.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_44.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_45.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_46.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_47.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_48.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_49.png"
            ],
            "position": [2144, 136]
        },
        {
            "id": "bird15",
            "image": "img/krabi/Seagull3.json",
            "frames": [
                "img/krabi/Krabi_Gull3/Krabi_Gull3_00.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_01.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_02.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_03.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_04.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_05.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_06.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_07.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_08.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_09.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_10.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_11.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_12.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_13.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_14.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_15.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_16.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_17.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_18.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_19.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_20.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_21.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_22.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_23.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_24.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_25.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_26.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_27.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_28.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_29.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_30.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_31.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_32.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_33.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_34.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_35.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_36.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_37.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_38.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_39.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_40.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_41.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_42.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_43.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_44.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_45.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_46.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_47.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_48.png",
                "img/krabi/Krabi_Gull3/Krabi_Gull3_49.png"
            ],
            "position": [2152, 295]
        },
        {
            "id": "cloud1",
            "image": "img/krabi/Clouds.json",
            "frames": ["img/krabi/Clouds_1.png"],
            "position": [91, 62]
        },
        {
            "id": "cloud2",
            "image": "img/krabi/Clouds.json",
            "frames": ["img/krabi/Clouds_2.png"],
            "position": [453, 19]
        },
        {
            "id": "cloud3",
            "image": "img/krabi/Clouds.json",
            "frames": ["img/krabi/Clouds_3.png"],
            "position": [518, 59]
        },
        {
            "id": "cloud4",
            "image": "img/krabi/Clouds.json",
            "frames": ["img/krabi/Clouds_4.png"],
            "position": [1045,  9]
        },
        {
            "id": "cloud5",
            "image": "img/krabi/Clouds.json",
            "frames": ["img/krabi/Clouds_5.png"],
            "position": [1327, 70]
        },
        {
            "id": "cloud6",
            "image": "img/krabi/Clouds.json",
            "frames": ["img/krabi/Clouds_6.png"],
            "position": [1431, 72]
        },
        {
            "id": "cloud7",
            "image": "img/krabi/Clouds.json",
            "frames": ["img/krabi/Clouds_7.png"],
            "position": [1692, 25]
        },
        {
            "id": "cloud8",
            "image": "img/krabi/Clouds.json",
            "frames": ["img/krabi/Clouds_8.png"],
            "position": [1705, 64]
        },
        {
            "id": "cloud9",
            "image": "img/krabi/Clouds.json",
            "frames": ["img/krabi/Clouds_9.png"],
            "position": [1806, 19]
        },
        {
            "id": "cloud10",
            "image": "img/krabi/Clouds.json",
            "frames": ["img/krabi/Clouds_10.png"],
            "position": [2022, 67]
        }
    ],
    "hitAreas": [],
    "config": {
        "cloud": {
            "speed": 70,
            "yMin": 0,
            "yMax": 350,
            "sceneWidth": sceneWidth,
            "speedVariance": 0.5
        },
        "birds": {
            "amplitude": 100,
            "duration": 2
        },
        "boats": {
            "amplitude": 25,
            "duration": 7
        },
        "boatTrack1": {
            "object": "movingBoat1",
            "track": [
                { "x": 493.780, "y": 1175.670 },
                { "x": 483.100, "y": 1162.930 },
                { "x": 475.800, "y": 1149.000 },
                { "x": 474.440, "y": 1138.290 },
                { "x": 485.520, "y": 1122.950 },
                { "x": 497.580, "y": 1113.180 },
                { "x": 521.000, "y": 1105.320 },
                { "x": 548.280, "y": 1100.780 },
                { "x": 570.910, "y": 1094.110 },
                { "x": 598.000, "y": 1088.000 },
                { "x": 624.000, "y": 1082.590 },
                { "x": 651.000, "y": 1077.600 },
                { "x": 674.000, "y": 1071.610 },
                { "x": 692.000, "y": 1064.590 },
                { "x": 709.000, "y": 1062.050 },
                { "x": 733.000, "y": 1062.050 },
                { "x": 762.000, "y": 1059.860 },
                { "x": 780.000, "y": 1056.000 },
                { "x": 835.000, "y": 1045.630 },
                { "x": 853.830, "y": 1041.530 },
                { "x": 868.000, "y": 1038.000 },
                { "x": 930.000, "y": 1038.000 },
                { "x": 963.000, "y": 1034.050 },
                { "x": 988.000, "y": 1032.000 },
                { "x": 1038.000, "y": 1026.000 },
                { "x": 1092.000, "y": 1024.050 },
                { "x": 1111.000, "y": 1022.000 },
                { "x": 1170.000, "y": 1022.000 },
                { "x": 1187.000, "y": 1024.000 },
                { "x": 1209.000, "y": 1024.000 },
                { "x": 1227.000, "y": 1026.000 },
                { "x": 1271.000, "y": 1038.650 },
                { "x": 1284.910, "y": 1043.820 },
                { "x": 1299.920, "y": 1054.240 },
                { "x": 1309.190, "y": 1069.510 },
                { "x": 1314.220, "y": 1084.950 },
                { "x": 1301.960, "y": 1104.310 },
                { "x": 1284.800, "y": 1117.750 },
                { "x": 1255.000, "y": 1124.000 },
                { "x": 1218.000, "y": 1114.000 },
                { "x": 1177.830, "y": 1100.350 },
                { "x": 1151.000, "y": 1092.390 },
                { "x": 1134.000, "y": 1088.590 },
                { "x": 1112.000, "y": 1086.000 },
                { "x": 1079.000, "y": 1086.000 },
                { "x": 1009.000, "y": 1084.000 },
                { "x": 961.000, "y": 1090.150 },
                { "x": 932.000, "y": 1094.000 },
                { "x": 888.000, "y": 1103.490 },
                { "x": 860.000, "y": 1110.320 },
                { "x": 835.050, "y": 1115.880 },
                { "x": 807.000, "y": 1127.800 },
                { "x": 778.000, "y": 1140.900 },
                { "x": 752.000, "y": 1148.460 },
                { "x": 726.000, "y": 1154.610 },
                { "x": 689.000, "y": 1167.410 },
                { "x": 642.000, "y": 1180.000 },
                { "x": 578.000, "y": 1188.000 },
                { "x": 534.000, "y": 1188.000 },
                { "x": 506.000, "y": 1186.090 },
                { "x": 493.780, "y": 1175.670 }
            ],
            "duration": 40
        },
        "boatTrack2": {
            "object": "movingBoat2",
            "track": [
                { "x": 301.630, "y": 1105.000 },
                { "x": 318.470, "y": 1067.010 },
                { "x": 329.130, "y": 1051.370 },
                { "x": 351.000, "y": 1036.990 },
                { "x": 386.570, "y": 1007.000 },
                { "x": 414.000, "y": 986.690 },
                { "x": 440.000, "y": 975.960 },
                { "x": 479.000, "y": 957.170 },
                { "x": 506.000, "y": 944.750 },
                { "x": 534.910, "y": 929.680 },
                { "x": 565.760, "y": 902.800 },
                { "x": 591.600, "y": 872.910 },
                { "x": 617.160, "y": 843.710 },
                { "x": 661.000, "y": 820.000 },
                { "x": 699.000, "y": 826.290 },
                { "x": 729.000, "y": 837.340 },
                { "x": 761.000, "y": 847.000 },
                { "x": 795.000, "y": 845.000 },
                { "x": 837.000, "y": 848.520 },
                { "x": 867.580, "y": 865.600 },
                { "x": 885.000, "y": 899.000 },
                { "x": 875.590, "y": 942.960 },
                { "x": 832.000, "y": 974.310 },
                { "x": 779.000, "y": 994.000 },
                { "x": 725.000, "y": 997.590 },
                { "x": 691.000, "y": 1010.460 },
                { "x": 648.000, "y": 1023.000 },
                { "x": 615.000, "y": 1028.640 },
                { "x": 582.000, "y": 1038.820 },
                { "x": 545.000, "y": 1049.000 },
                { "x": 482.000, "y": 1048.290 },
                { "x": 453.720, "y": 1058.480 },
                { "x": 427.250, "y": 1069.770 },
                { "x": 415.960, "y": 1093.000 },
                { "x": 408.110, "y": 1128.980 },
                { "x": 388.000, "y": 1154.000 },
                { "x": 357.000, "y": 1160.000 },
                { "x": 316.060, "y": 1153.740 },
                { "x": 308.920, "y": 1131.000 },
                { "x": 301.630, "y": 1105.000 }
            ],
            "duration": 40,
        },
        "boatTrack3": {
            "object": "movingBoat4",
            "track": [
                { "x": 812.000, "y": 840.280 },
                { "x": 780.000, "y": 836.860 },
                { "x": 753.000, "y": 828.380 },
                { "x": 722.730, "y": 812.050 },
                { "x": 699.660, "y": 784.830 },
                { "x": 696.000, "y": 746.000 },
                { "x": 707.190, "y": 699.170 },
                { "x": 747.000, "y": 673.420 },
                { "x": 774.000, "y": 672.000 },
                { "x": 804.000, "y": 675.000 },
                { "x": 837.000, "y": 673.100 },
                { "x": 890.000, "y": 662.410 },
                { "x": 931.000, "y": 650.370 },
                { "x": 971.000, "y": 642.000 },
                { "x": 1018.000, "y": 642.000 },
                { "x": 1059.000, "y": 646.700 },
                { "x": 1115.000, "y": 661.140 },
                { "x": 1153.900, "y": 689.180 },
                { "x": 1159.000, "y": 723.000 },
                { "x": 1137.910, "y": 769.510 },
                { "x": 1111.000, "y": 782.170 },
                { "x": 1082.000, "y": 791.910 },
                { "x": 1042.000, "y": 803.000 },
                { "x": 997.000, "y": 803.000 },
                { "x": 967.000, "y": 801.000 },
                { "x": 920.360, "y": 800.420 },
                { "x": 870.010, "y": 810.740 },
                { "x": 852.630, "y": 825.980 },
                { "x": 812.000, "y": 840.280 }
            ],
            "duration": 40
        },
        "boatTrack4": {
            "object": "movingBoat3",
            "track": [
                { "x": 1205.000, "y": 808.000 },
                { "x": 1276.000, "y": 830.550 },
                { "x": 1327.000, "y": 835.000 },
                { "x": 1370.000, "y": 837.630 },
                { "x": 1405.870, "y": 861.390 },
                { "x": 1423.370, "y": 876.320 },
                { "x": 1428.000, "y": 916.000 },
                { "x": 1425.440, "y": 945.170 },
                { "x": 1400.130, "y": 985.280 },
                { "x": 1357.000, "y": 1009.000 },
                { "x": 1323.000, "y": 1009.000 },
                { "x": 1300.440, "y": 1004.190 },
                { "x": 1265.280, "y": 989.620 },
                { "x": 1218.000, "y": 970.460 },
                { "x": 1169.000, "y": 963.050 },
                { "x": 1124.000, "y": 959.910 },
                { "x": 1110.000, "y": 958.000 },
                { "x": 1073.000, "y": 960.000 },
                { "x": 1024.650, "y": 964.150 },
                { "x": 1002.100, "y": 977.350 },
                { "x": 979.000, "y": 978.000 },
                { "x": 954.000, "y": 970.260 },
                { "x": 924.000, "y": 927.000 },
                { "x": 924.000, "y": 884.950 },
                { "x": 940.830, "y": 857.000 },
                { "x": 958.460, "y": 836.250 },
                { "x": 998.000, "y": 821.620 },
                { "x": 1071.000, "y": 816.000 },
                { "x": 1119.000, "y": 814.000 },
                { "x": 1163.000, "y": 811.000 },
                { "x": 1205.000, "y": 808.000 }
            ],
            "duration": 40
        },
        "boatTrack5": {
            "object": "movingBoat4",
            "track": [
                { "x": 1195.620, "y": 704.380 },
                { "x": 1181.880, "y": 677.500 },
                { "x": 1158.750, "y": 641.250 },
                { "x": 1162.500, "y": 596.880 },
                { "x": 1175.620, "y": 562.500 },
                { "x": 1194.970, "y": 540.640 },
                { "x": 1220.000, "y": 546.880 },
                { "x": 1248.830, "y": 567.010 },
                { "x": 1277.000, "y": 603.170 },
                { "x": 1304.270, "y": 638.000 },
                { "x": 1329.130, "y": 667.270 },
                { "x": 1371.280, "y": 699.160 },
                { "x": 1434.000, "y": 736.520 },
                { "x": 1467.000, "y": 746.790 },
                { "x": 1486.000, "y": 748.260 },
                { "x": 1535.830, "y": 776.470 },
                { "x": 1558.750, "y": 794.380 },
                { "x": 1566.880, "y": 818.750 },
                { "x": 1583.800, "y": 841.280 },
                { "x": 1599.900, "y": 871.000 },
                { "x": 1607.900, "y": 905.000 },
                { "x": 1607.000, "y": 958.000 },
                { "x": 1591.280, "y": 1001.540 },
                { "x": 1572.000, "y": 1016.360 },
                { "x": 1526.960, "y": 1008.600 },
                { "x": 1495.090, "y": 996.190 },
                { "x": 1468.750, "y": 970.620 },
                { "x": 1459.000, "y": 929.000 },
                { "x": 1459.000, "y": 904.000 },
                { "x": 1461.000, "y": 888.000 },
                { "x": 1450.570, "y": 841.460 },
                { "x": 1429.090, "y": 829.040 },
                { "x": 1389.000, "y": 809.570 },
                { "x": 1372.000, "y": 805.000 },
                { "x": 1341.000, "y": 803.760 },
                { "x": 1305.620, "y": 794.380 },
                { "x": 1273.000, "y": 779.980 },
                { "x": 1237.060, "y": 761.080 },
                { "x": 1217.520, "y": 735.290 },
                { "x": 1195.620, "y": 704.380 }
            ],
            "duration": 40
        }
    }
};
