var sceneWidth = 2304;

module.exports = {
    "name": "Rome",
    "lat": 12.395912, //12.395912,
    "lon": 41.909986, //41.909986,
    "sceneWidth": sceneWidth,
    "sceneHeight": 1440,
    "objects": [
        {
            "id": "background",
            "image": "img/rome/rome-back.jpg",
            "position": [0, 0]
        },
        {
            "id": "car1",
            "image": "img/common/Car1.json",
            "frames": [
                "img/common/Car1/Car1_00.png",
                "img/common/Car1/Car1_01.png",
                "img/common/Car1/Car1_02.png",
                "img/common/Car1/Car1_03.png",
                "img/common/Car1/Car1_04.png",
                "img/common/Car1/Car1_05.png",
                "img/common/Car1/Car1_06.png",
                "img/common/Car1/Car1_07.png",
                "img/common/Car1/Car1_08.png",
                "img/common/Car1/Car1_09.png",
                "img/common/Car1/Car1_10.png",
                "img/common/Car1/Car1_11.png",
                "img/common/Car1/Car1_12.png",
                "img/common/Car1/Car1_13.png",
                "img/common/Car1/Car1_14.png",
                "img/common/Car1/Car1_15.png",
                "img/common/Car1/Car1_16.png",
                "img/common/Car1/Car1_17.png",
                "img/common/Car1/Car1_18.png",
                "img/common/Car1/Car1_19.png",
                "img/common/Car1/Car1_20.png",
                "img/common/Car1/Car1_21.png",
                "img/common/Car1/Car1_22.png",
                "img/common/Car1/Car1_23.png",
                "img/common/Car1/Car1_24.png",
                "img/common/Car1/Car1_25.png",
                "img/common/Car1/Car1_26.png",
                "img/common/Car1/Car1_27.png",
                "img/common/Car1/Car1_28.png",
                "img/common/Car1/Car1_29.png",
                "img/common/Car1/Car1_30.png",
                "img/common/Car1/Car1_31.png",
                "img/common/Car1/Car1_32.png",
                "img/common/Car1/Car1_33.png",
                "img/common/Car1/Car1_34.png",
                "img/common/Car1/Car1_35.png",
                "img/common/Car1/Car1_36.png",
                "img/common/Car1/Car1_37.png",
                "img/common/Car1/Car1_38.png",
                "img/common/Car1/Car1_39.png",
                "img/common/Car1/Car1_40.png",
                "img/common/Car1/Car1_41.png",
                "img/common/Car1/Car1_42.png",
                "img/common/Car1/Car1_43.png",
                "img/common/Car1/Car1_44.png",
                "img/common/Car1/Car1_45.png",
                "img/common/Car1/Car1_46.png",
                "img/common/Car1/Car1_47.png",
                "img/common/Car1/Car1_48.png",
                "img/common/Car1/Car1_49.png",
                "img/common/Car1/Car1_50.png",
                "img/common/Car1/Car1_51.png",
                "img/common/Car1/Car1_52.png",
                "img/common/Car1/Car1_53.png",
                "img/common/Car1/Car1_54.png",
                "img/common/Car1/Car1_55.png",
                "img/common/Car1/Car1_56.png",
                "img/common/Car1/Car1_57.png",
                "img/common/Car1/Car1_58.png",
                "img/common/Car1/Car1_59.png",
                "img/common/Car1/Car1_60.png",
                "img/common/Car1/Car1_61.png",
                "img/common/Car1/Car1_62.png",
                "img/common/Car1/Car1_63.png",
                "img/common/Car1/Car1_64.png",
                "img/common/Car1/Car1_65.png",
                "img/common/Car1/Car1_66.png",
                "img/common/Car1/Car1_67.png",
                "img/common/Car1/Car1_68.png",
                "img/common/Car1/Car1_69.png",
                "img/common/Car1/Car1_70.png",
                "img/common/Car1/Car1_71.png",
                "img/common/Car1/Car1_72.png",
                "img/common/Car1/Car1_73.png",
                "img/common/Car1/Car1_74.png",
                "img/common/Car1/Car1_75.png",
                "img/common/Car1/Car1_76.png",
                "img/common/Car1/Car1_77.png",
                "img/common/Car1/Car1_78.png",
                "img/common/Car1/Car1_79.png",
                "img/common/Car1/Car1_80.png",
                "img/common/Car1/Car1_81.png",
                "img/common/Car1/Car1_82.png",
                "img/common/Car1/Car1_83.png",
                "img/common/Car1/Car1_84.png",
                "img/common/Car1/Car1_85.png",
                "img/common/Car1/Car1_86.png",
                "img/common/Car1/Car1_87.png",
                "img/common/Car1/Car1_88.png",
                "img/common/Car1/Car1_89.png",
                "img/common/Car1/Car1_90.png",
                "img/common/Car1/Car1_91.png",
                "img/common/Car1/Car1_92.png",
                "img/common/Car1/Car1_93.png",
                "img/common/Car1/Car1_94.png",
                "img/common/Car1/Car1_95.png"
            ]
        },
        {
            "id": "car2",
            "image": "img/common/Car2.json",
            "frames": [
                "img/common/Car2/Car2_00.png",
                "img/common/Car2/Car2_01.png",
                "img/common/Car2/Car2_02.png",
                "img/common/Car2/Car2_03.png",
                "img/common/Car2/Car2_04.png",
                "img/common/Car2/Car2_05.png",
                "img/common/Car2/Car2_06.png",
                "img/common/Car2/Car2_07.png",
                "img/common/Car2/Car2_08.png",
                "img/common/Car2/Car2_09.png",
                "img/common/Car2/Car2_10.png",
                "img/common/Car2/Car2_11.png",
                "img/common/Car2/Car2_12.png",
                "img/common/Car2/Car2_13.png",
                "img/common/Car2/Car2_14.png",
                "img/common/Car2/Car2_15.png",
                "img/common/Car2/Car2_16.png",
                "img/common/Car2/Car2_17.png",
                "img/common/Car2/Car2_18.png",
                "img/common/Car2/Car2_19.png",
                "img/common/Car2/Car2_20.png",
                "img/common/Car2/Car2_21.png",
                "img/common/Car2/Car2_22.png",
                "img/common/Car2/Car2_23.png",
                "img/common/Car2/Car2_24.png",
                "img/common/Car2/Car2_25.png",
                "img/common/Car2/Car2_26.png",
                "img/common/Car2/Car2_27.png",
                "img/common/Car2/Car2_28.png",
                "img/common/Car2/Car2_29.png",
                "img/common/Car2/Car2_30.png",
                "img/common/Car2/Car2_31.png",
                "img/common/Car2/Car2_32.png",
                "img/common/Car2/Car2_33.png",
                "img/common/Car2/Car2_34.png",
                "img/common/Car2/Car2_35.png",
                "img/common/Car2/Car2_36.png",
                "img/common/Car2/Car2_37.png",
                "img/common/Car2/Car2_38.png",
                "img/common/Car2/Car2_39.png",
                "img/common/Car2/Car2_40.png",
                "img/common/Car2/Car2_41.png",
                "img/common/Car2/Car2_42.png",
                "img/common/Car2/Car2_43.png",
                "img/common/Car2/Car2_44.png",
                "img/common/Car2/Car2_45.png",
                "img/common/Car2/Car2_46.png",
                "img/common/Car2/Car2_47.png",
                "img/common/Car2/Car2_48.png",
                "img/common/Car2/Car2_49.png",
                "img/common/Car2/Car2_50.png",
                "img/common/Car2/Car2_51.png",
                "img/common/Car2/Car2_52.png",
                "img/common/Car2/Car2_53.png",
                "img/common/Car2/Car2_54.png",
                "img/common/Car2/Car2_55.png",
                "img/common/Car2/Car2_56.png",
                "img/common/Car2/Car2_57.png",
                "img/common/Car2/Car2_58.png",
                "img/common/Car2/Car2_59.png",
                "img/common/Car2/Car2_60.png",
                "img/common/Car2/Car2_61.png",
                "img/common/Car2/Car2_62.png",
                "img/common/Car2/Car2_63.png",
                "img/common/Car2/Car2_64.png",
                "img/common/Car2/Car2_65.png",
                "img/common/Car2/Car2_66.png",
                "img/common/Car2/Car2_67.png",
                "img/common/Car2/Car2_68.png",
                "img/common/Car2/Car2_69.png",
                "img/common/Car2/Car2_70.png",
                "img/common/Car2/Car2_71.png",
                "img/common/Car2/Car2_72.png",
                "img/common/Car2/Car2_73.png",
                "img/common/Car2/Car2_74.png",
                "img/common/Car2/Car2_75.png",
                "img/common/Car2/Car2_76.png",
                "img/common/Car2/Car2_77.png",
                "img/common/Car2/Car2_78.png",
                "img/common/Car2/Car2_79.png",
                "img/common/Car2/Car2_80.png",
                "img/common/Car2/Car2_81.png",
                "img/common/Car2/Car2_82.png",
                "img/common/Car2/Car2_83.png",
                "img/common/Car2/Car2_84.png",
                "img/common/Car2/Car2_85.png",
                "img/common/Car2/Car2_86.png",
                "img/common/Car2/Car2_87.png",
                "img/common/Car2/Car2_88.png",
                "img/common/Car2/Car2_89.png",
                "img/common/Car2/Car2_90.png",
                "img/common/Car2/Car2_91.png",
                "img/common/Car2/Car2_92.png",
                "img/common/Car2/Car2_93.png",
                "img/common/Car2/Car2_94.png",
                "img/common/Car2/Car2_95.png"
            ]
        },
        {
            "id": "car3",
            "image": "img/common/Car3.json",
            "frames": [
                "img/common/Car3/Car3_00.png",
                "img/common/Car3/Car3_01.png",
                "img/common/Car3/Car3_02.png",
                "img/common/Car3/Car3_03.png",
                "img/common/Car3/Car3_04.png",
                "img/common/Car3/Car3_05.png",
                "img/common/Car3/Car3_06.png",
                "img/common/Car3/Car3_07.png",
                "img/common/Car3/Car3_08.png",
                "img/common/Car3/Car3_09.png",
                "img/common/Car3/Car3_10.png",
                "img/common/Car3/Car3_11.png",
                "img/common/Car3/Car3_12.png",
                "img/common/Car3/Car3_13.png",
                "img/common/Car3/Car3_14.png",
                "img/common/Car3/Car3_15.png",
                "img/common/Car3/Car3_16.png",
                "img/common/Car3/Car3_17.png",
                "img/common/Car3/Car3_18.png",
                "img/common/Car3/Car3_19.png",
                "img/common/Car3/Car3_20.png",
                "img/common/Car3/Car3_21.png",
                "img/common/Car3/Car3_22.png",
                "img/common/Car3/Car3_23.png",
                "img/common/Car3/Car3_24.png",
                "img/common/Car3/Car3_25.png",
                "img/common/Car3/Car3_26.png",
                "img/common/Car3/Car3_27.png",
                "img/common/Car3/Car3_28.png",
                "img/common/Car3/Car3_29.png",
                "img/common/Car3/Car3_30.png",
                "img/common/Car3/Car3_31.png",
                "img/common/Car3/Car3_32.png",
                "img/common/Car3/Car3_33.png",
                "img/common/Car3/Car3_34.png",
                "img/common/Car3/Car3_35.png",
                "img/common/Car3/Car3_36.png",
                "img/common/Car3/Car3_37.png",
                "img/common/Car3/Car3_38.png",
                "img/common/Car3/Car3_39.png",
                "img/common/Car3/Car3_40.png",
                "img/common/Car3/Car3_41.png",
                "img/common/Car3/Car3_42.png",
                "img/common/Car3/Car3_43.png",
                "img/common/Car3/Car3_44.png",
                "img/common/Car3/Car3_45.png",
                "img/common/Car3/Car3_46.png",
                "img/common/Car3/Car3_47.png",
                "img/common/Car3/Car3_48.png",
                "img/common/Car3/Car3_49.png",
                "img/common/Car3/Car3_50.png",
                "img/common/Car3/Car3_51.png",
                "img/common/Car3/Car3_52.png",
                "img/common/Car3/Car3_53.png",
                "img/common/Car3/Car3_54.png",
                "img/common/Car3/Car3_55.png",
                "img/common/Car3/Car3_56.png",
                "img/common/Car3/Car3_57.png",
                "img/common/Car3/Car3_58.png",
                "img/common/Car3/Car3_59.png",
                "img/common/Car3/Car3_60.png",
                "img/common/Car3/Car3_61.png",
                "img/common/Car3/Car3_62.png",
                "img/common/Car3/Car3_63.png",
                "img/common/Car3/Car3_64.png",
                "img/common/Car3/Car3_65.png",
                "img/common/Car3/Car3_66.png",
                "img/common/Car3/Car3_67.png",
                "img/common/Car3/Car3_68.png",
                "img/common/Car3/Car3_69.png",
                "img/common/Car3/Car3_70.png",
                "img/common/Car3/Car3_71.png",
                "img/common/Car3/Car3_72.png",
                "img/common/Car3/Car3_73.png",
                "img/common/Car3/Car3_74.png",
                "img/common/Car3/Car3_75.png",
                "img/common/Car3/Car3_76.png",
                "img/common/Car3/Car3_77.png",
                "img/common/Car3/Car3_78.png",
                "img/common/Car3/Car3_79.png",
                "img/common/Car3/Car3_80.png",
                "img/common/Car3/Car3_81.png",
                "img/common/Car3/Car3_82.png",
                "img/common/Car3/Car3_83.png",
                "img/common/Car3/Car3_84.png",
                "img/common/Car3/Car3_85.png",
                "img/common/Car3/Car3_86.png",
                "img/common/Car3/Car3_87.png",
                "img/common/Car3/Car3_88.png",
                "img/common/Car3/Car3_89.png",
                "img/common/Car3/Car3_90.png",
                "img/common/Car3/Car3_91.png",
                "img/common/Car3/Car3_92.png",
                "img/common/Car3/Car3_93.png",
                "img/common/Car3/Car3_94.png",
                "img/common/Car3/Car3_95.png"
            ]
        },
        {
            "id": "car4",
            "image": "img/common/Car4.json",
            "frames": [
                "img/common/Car4/Car4_00.png",
                "img/common/Car4/Car4_01.png",
                "img/common/Car4/Car4_02.png",
                "img/common/Car4/Car4_03.png",
                "img/common/Car4/Car4_04.png",
                "img/common/Car4/Car4_05.png",
                "img/common/Car4/Car4_06.png",
                "img/common/Car4/Car4_07.png",
                "img/common/Car4/Car4_08.png",
                "img/common/Car4/Car4_09.png",
                "img/common/Car4/Car4_10.png",
                "img/common/Car4/Car4_11.png",
                "img/common/Car4/Car4_12.png",
                "img/common/Car4/Car4_13.png",
                "img/common/Car4/Car4_14.png",
                "img/common/Car4/Car4_15.png",
                "img/common/Car4/Car4_16.png",
                "img/common/Car4/Car4_17.png",
                "img/common/Car4/Car4_18.png",
                "img/common/Car4/Car4_19.png",
                "img/common/Car4/Car4_20.png",
                "img/common/Car4/Car4_21.png",
                "img/common/Car4/Car4_22.png",
                "img/common/Car4/Car4_23.png",
                "img/common/Car4/Car4_24.png",
                "img/common/Car4/Car4_25.png",
                "img/common/Car4/Car4_26.png",
                "img/common/Car4/Car4_27.png",
                "img/common/Car4/Car4_28.png",
                "img/common/Car4/Car4_29.png",
                "img/common/Car4/Car4_30.png",
                "img/common/Car4/Car4_31.png",
                "img/common/Car4/Car4_32.png",
                "img/common/Car4/Car4_33.png",
                "img/common/Car4/Car4_34.png",
                "img/common/Car4/Car4_35.png",
                "img/common/Car4/Car4_36.png",
                "img/common/Car4/Car4_37.png",
                "img/common/Car4/Car4_38.png",
                "img/common/Car4/Car4_39.png",
                "img/common/Car4/Car4_40.png",
                "img/common/Car4/Car4_41.png",
                "img/common/Car4/Car4_42.png",
                "img/common/Car4/Car4_43.png",
                "img/common/Car4/Car4_44.png",
                "img/common/Car4/Car4_45.png",
                "img/common/Car4/Car4_46.png",
                "img/common/Car4/Car4_47.png",
                "img/common/Car4/Car4_48.png",
                "img/common/Car4/Car4_49.png",
                "img/common/Car4/Car4_50.png",
                "img/common/Car4/Car4_51.png",
                "img/common/Car4/Car4_52.png",
                "img/common/Car4/Car4_53.png",
                "img/common/Car4/Car4_54.png",
                "img/common/Car4/Car4_55.png",
                "img/common/Car4/Car4_56.png",
                "img/common/Car4/Car4_57.png",
                "img/common/Car4/Car4_58.png",
                "img/common/Car4/Car4_59.png",
                "img/common/Car4/Car4_60.png",
                "img/common/Car4/Car4_61.png",
                "img/common/Car4/Car4_62.png",
                "img/common/Car4/Car4_63.png",
                "img/common/Car4/Car4_64.png",
                "img/common/Car4/Car4_65.png",
                "img/common/Car4/Car4_66.png",
                "img/common/Car4/Car4_67.png",
                "img/common/Car4/Car4_68.png",
                "img/common/Car4/Car4_69.png",
                "img/common/Car4/Car4_70.png",
                "img/common/Car4/Car4_71.png",
                "img/common/Car4/Car4_72.png",
                "img/common/Car4/Car4_73.png",
                "img/common/Car4/Car4_74.png",
                "img/common/Car4/Car4_75.png",
                "img/common/Car4/Car4_76.png",
                "img/common/Car4/Car4_77.png",
                "img/common/Car4/Car4_78.png",
                "img/common/Car4/Car4_79.png",
                "img/common/Car4/Car4_80.png",
                "img/common/Car4/Car4_81.png",
                "img/common/Car4/Car4_82.png",
                "img/common/Car4/Car4_83.png",
                "img/common/Car4/Car4_84.png",
                "img/common/Car4/Car4_85.png",
                "img/common/Car4/Car4_86.png",
                "img/common/Car4/Car4_87.png",
                "img/common/Car4/Car4_88.png",
                "img/common/Car4/Car4_89.png",
                "img/common/Car4/Car4_90.png",
                "img/common/Car4/Car4_91.png",
                "img/common/Car4/Car4_92.png",
                "img/common/Car4/Car4_93.png",
                "img/common/Car4/Car4_94.png",
                "img/common/Car4/Car4_95.png"
            ]
        },
        {
            "id": "car5",
            "image": "img/common/Car5.json",
            "frames": [
                "img/common/Car5/Car5_00.png",
                "img/common/Car5/Car5_01.png",
                "img/common/Car5/Car5_02.png",
                "img/common/Car5/Car5_03.png",
                "img/common/Car5/Car5_04.png",
                "img/common/Car5/Car5_05.png",
                "img/common/Car5/Car5_06.png",
                "img/common/Car5/Car5_07.png",
                "img/common/Car5/Car5_08.png",
                "img/common/Car5/Car5_09.png",
                "img/common/Car5/Car5_10.png",
                "img/common/Car5/Car5_11.png",
                "img/common/Car5/Car5_12.png",
                "img/common/Car5/Car5_13.png",
                "img/common/Car5/Car5_14.png",
                "img/common/Car5/Car5_15.png",
                "img/common/Car5/Car5_16.png",
                "img/common/Car5/Car5_17.png",
                "img/common/Car5/Car5_18.png",
                "img/common/Car5/Car5_19.png",
                "img/common/Car5/Car5_20.png",
                "img/common/Car5/Car5_21.png",
                "img/common/Car5/Car5_22.png",
                "img/common/Car5/Car5_23.png",
                "img/common/Car5/Car5_24.png",
                "img/common/Car5/Car5_25.png",
                "img/common/Car5/Car5_26.png",
                "img/common/Car5/Car5_27.png",
                "img/common/Car5/Car5_28.png",
                "img/common/Car5/Car5_29.png",
                "img/common/Car5/Car5_30.png",
                "img/common/Car5/Car5_31.png",
                "img/common/Car5/Car5_32.png",
                "img/common/Car5/Car5_33.png",
                "img/common/Car5/Car5_34.png",
                "img/common/Car5/Car5_35.png",
                "img/common/Car5/Car5_36.png",
                "img/common/Car5/Car5_37.png",
                "img/common/Car5/Car5_38.png",
                "img/common/Car5/Car5_39.png",
                "img/common/Car5/Car5_40.png",
                "img/common/Car5/Car5_41.png",
                "img/common/Car5/Car5_42.png",
                "img/common/Car5/Car5_43.png",
                "img/common/Car5/Car5_44.png",
                "img/common/Car5/Car5_45.png",
                "img/common/Car5/Car5_46.png",
                "img/common/Car5/Car5_47.png",
                "img/common/Car5/Car5_48.png",
                "img/common/Car5/Car5_49.png",
                "img/common/Car5/Car5_50.png",
                "img/common/Car5/Car5_51.png",
                "img/common/Car5/Car5_52.png",
                "img/common/Car5/Car5_53.png",
                "img/common/Car5/Car5_54.png",
                "img/common/Car5/Car5_55.png",
                "img/common/Car5/Car5_56.png",
                "img/common/Car5/Car5_57.png",
                "img/common/Car5/Car5_58.png",
                "img/common/Car5/Car5_59.png",
                "img/common/Car5/Car5_60.png",
                "img/common/Car5/Car5_61.png",
                "img/common/Car5/Car5_62.png",
                "img/common/Car5/Car5_63.png",
                "img/common/Car5/Car5_64.png",
                "img/common/Car5/Car5_65.png",
                "img/common/Car5/Car5_66.png",
                "img/common/Car5/Car5_67.png",
                "img/common/Car5/Car5_68.png",
                "img/common/Car5/Car5_69.png",
                "img/common/Car5/Car5_70.png",
                "img/common/Car5/Car5_71.png",
                "img/common/Car5/Car5_72.png",
                "img/common/Car5/Car5_73.png",
                "img/common/Car5/Car5_74.png",
                "img/common/Car5/Car5_75.png",
                "img/common/Car5/Car5_76.png",
                "img/common/Car5/Car5_77.png",
                "img/common/Car5/Car5_78.png",
                "img/common/Car5/Car5_79.png",
                "img/common/Car5/Car5_80.png",
                "img/common/Car5/Car5_81.png",
                "img/common/Car5/Car5_82.png",
                "img/common/Car5/Car5_83.png",
                "img/common/Car5/Car5_84.png",
                "img/common/Car5/Car5_85.png",
                "img/common/Car5/Car5_86.png",
                "img/common/Car5/Car5_87.png",
                "img/common/Car5/Car5_88.png",
                "img/common/Car5/Car5_89.png",
                "img/common/Car5/Car5_90.png",
                "img/common/Car5/Car5_91.png",
                "img/common/Car5/Car5_92.png",
                "img/common/Car5/Car5_93.png",
                "img/common/Car5/Car5_94.png",
                "img/common/Car5/Car5_95.png"
            ]
        },
        {
            "id": "car6",
            "image": "img/common/Car6.json",
            "frames": [
                "img/common/Car6/Car6_00.png",
                "img/common/Car6/Car6_01.png",
                "img/common/Car6/Car6_02.png",
                "img/common/Car6/Car6_03.png",
                "img/common/Car6/Car6_04.png",
                "img/common/Car6/Car6_05.png",
                "img/common/Car6/Car6_06.png",
                "img/common/Car6/Car6_07.png",
                "img/common/Car6/Car6_08.png",
                "img/common/Car6/Car6_09.png",
                "img/common/Car6/Car6_10.png",
                "img/common/Car6/Car6_11.png",
                "img/common/Car6/Car6_12.png",
                "img/common/Car6/Car6_13.png",
                "img/common/Car6/Car6_14.png",
                "img/common/Car6/Car6_15.png",
                "img/common/Car6/Car6_16.png",
                "img/common/Car6/Car6_17.png",
                "img/common/Car6/Car6_18.png",
                "img/common/Car6/Car6_19.png",
                "img/common/Car6/Car6_20.png",
                "img/common/Car6/Car6_21.png",
                "img/common/Car6/Car6_22.png",
                "img/common/Car6/Car6_23.png",
                "img/common/Car6/Car6_24.png",
                "img/common/Car6/Car6_25.png",
                "img/common/Car6/Car6_26.png",
                "img/common/Car6/Car6_27.png",
                "img/common/Car6/Car6_28.png",
                "img/common/Car6/Car6_29.png",
                "img/common/Car6/Car6_30.png",
                "img/common/Car6/Car6_31.png",
                "img/common/Car6/Car6_32.png",
                "img/common/Car6/Car6_33.png",
                "img/common/Car6/Car6_34.png",
                "img/common/Car6/Car6_35.png",
                "img/common/Car6/Car6_36.png",
                "img/common/Car6/Car6_37.png",
                "img/common/Car6/Car6_38.png",
                "img/common/Car6/Car6_39.png",
                "img/common/Car6/Car6_40.png",
                "img/common/Car6/Car6_41.png",
                "img/common/Car6/Car6_42.png",
                "img/common/Car6/Car6_43.png",
                "img/common/Car6/Car6_44.png",
                "img/common/Car6/Car6_45.png",
                "img/common/Car6/Car6_46.png",
                "img/common/Car6/Car6_47.png",
                "img/common/Car6/Car6_48.png",
                "img/common/Car6/Car6_49.png",
                "img/common/Car6/Car6_50.png",
                "img/common/Car6/Car6_51.png",
                "img/common/Car6/Car6_52.png",
                "img/common/Car6/Car6_53.png",
                "img/common/Car6/Car6_54.png",
                "img/common/Car6/Car6_55.png",
                "img/common/Car6/Car6_56.png",
                "img/common/Car6/Car6_57.png",
                "img/common/Car6/Car6_58.png",
                "img/common/Car6/Car6_59.png",
                "img/common/Car6/Car6_60.png",
                "img/common/Car6/Car6_61.png",
                "img/common/Car6/Car6_62.png",
                "img/common/Car6/Car6_63.png",
                "img/common/Car6/Car6_64.png",
                "img/common/Car6/Car6_65.png",
                "img/common/Car6/Car6_66.png",
                "img/common/Car6/Car6_67.png",
                "img/common/Car6/Car6_68.png",
                "img/common/Car6/Car6_69.png",
                "img/common/Car6/Car6_70.png",
                "img/common/Car6/Car6_71.png",
                "img/common/Car6/Car6_72.png",
                "img/common/Car6/Car6_73.png",
                "img/common/Car6/Car6_74.png",
                "img/common/Car6/Car6_75.png",
                "img/common/Car6/Car6_76.png",
                "img/common/Car6/Car6_77.png",
                "img/common/Car6/Car6_78.png",
                "img/common/Car6/Car6_79.png",
                "img/common/Car6/Car6_80.png",
                "img/common/Car6/Car6_81.png",
                "img/common/Car6/Car6_82.png",
                "img/common/Car6/Car6_83.png",
                "img/common/Car6/Car6_84.png",
                "img/common/Car6/Car6_85.png",
                "img/common/Car6/Car6_86.png",
                "img/common/Car6/Car6_87.png",
                "img/common/Car6/Car6_88.png",
                "img/common/Car6/Car6_89.png",
                "img/common/Car6/Car6_90.png",
                "img/common/Car6/Car6_91.png",
                "img/common/Car6/Car6_92.png",
                "img/common/Car6/Car6_93.png",
                "img/common/Car6/Car6_94.png",
                "img/common/Car6/Car6_95.png"
            ]
        },
        {
            "id": "car7",
            "image": "img/common/Car7.json",
            "frames": [
                "img/common/Car7/Car7_00.png",
                "img/common/Car7/Car7_01.png",
                "img/common/Car7/Car7_02.png",
                "img/common/Car7/Car7_03.png",
                "img/common/Car7/Car7_04.png",
                "img/common/Car7/Car7_05.png",
                "img/common/Car7/Car7_06.png",
                "img/common/Car7/Car7_07.png",
                "img/common/Car7/Car7_08.png",
                "img/common/Car7/Car7_09.png",
                "img/common/Car7/Car7_10.png",
                "img/common/Car7/Car7_11.png",
                "img/common/Car7/Car7_12.png",
                "img/common/Car7/Car7_13.png",
                "img/common/Car7/Car7_14.png",
                "img/common/Car7/Car7_15.png",
                "img/common/Car7/Car7_16.png",
                "img/common/Car7/Car7_17.png",
                "img/common/Car7/Car7_18.png",
                "img/common/Car7/Car7_19.png",
                "img/common/Car7/Car7_20.png",
                "img/common/Car7/Car7_21.png",
                "img/common/Car7/Car7_22.png",
                "img/common/Car7/Car7_23.png",
                "img/common/Car7/Car7_24.png",
                "img/common/Car7/Car7_25.png",
                "img/common/Car7/Car7_26.png",
                "img/common/Car7/Car7_27.png",
                "img/common/Car7/Car7_28.png",
                "img/common/Car7/Car7_29.png",
                "img/common/Car7/Car7_30.png",
                "img/common/Car7/Car7_31.png",
                "img/common/Car7/Car7_32.png",
                "img/common/Car7/Car7_33.png",
                "img/common/Car7/Car7_34.png",
                "img/common/Car7/Car7_35.png",
                "img/common/Car7/Car7_36.png",
                "img/common/Car7/Car7_37.png",
                "img/common/Car7/Car7_38.png",
                "img/common/Car7/Car7_39.png",
                "img/common/Car7/Car7_40.png",
                "img/common/Car7/Car7_41.png",
                "img/common/Car7/Car7_42.png",
                "img/common/Car7/Car7_43.png",
                "img/common/Car7/Car7_44.png",
                "img/common/Car7/Car7_45.png",
                "img/common/Car7/Car7_46.png",
                "img/common/Car7/Car7_47.png",
                "img/common/Car7/Car7_48.png",
                "img/common/Car7/Car7_49.png",
                "img/common/Car7/Car7_50.png",
                "img/common/Car7/Car7_51.png",
                "img/common/Car7/Car7_52.png",
                "img/common/Car7/Car7_53.png",
                "img/common/Car7/Car7_54.png",
                "img/common/Car7/Car7_55.png",
                "img/common/Car7/Car7_56.png",
                "img/common/Car7/Car7_57.png",
                "img/common/Car7/Car7_58.png",
                "img/common/Car7/Car7_59.png",
                "img/common/Car7/Car7_60.png",
                "img/common/Car7/Car7_61.png",
                "img/common/Car7/Car7_62.png",
                "img/common/Car7/Car7_63.png",
                "img/common/Car7/Car7_64.png",
                "img/common/Car7/Car7_65.png",
                "img/common/Car7/Car7_66.png",
                "img/common/Car7/Car7_67.png",
                "img/common/Car7/Car7_68.png",
                "img/common/Car7/Car7_69.png",
                "img/common/Car7/Car7_70.png",
                "img/common/Car7/Car7_71.png",
                "img/common/Car7/Car7_72.png",
                "img/common/Car7/Car7_73.png",
                "img/common/Car7/Car7_74.png",
                "img/common/Car7/Car7_75.png",
                "img/common/Car7/Car7_76.png",
                "img/common/Car7/Car7_77.png",
                "img/common/Car7/Car7_78.png",
                "img/common/Car7/Car7_79.png",
                "img/common/Car7/Car7_80.png",
                "img/common/Car7/Car7_81.png",
                "img/common/Car7/Car7_82.png",
                "img/common/Car7/Car7_83.png",
                "img/common/Car7/Car7_84.png",
                "img/common/Car7/Car7_85.png",
                "img/common/Car7/Car7_86.png",
                "img/common/Car7/Car7_87.png",
                "img/common/Car7/Car7_88.png",
                "img/common/Car7/Car7_89.png",
                "img/common/Car7/Car7_90.png",
                "img/common/Car7/Car7_91.png",
                "img/common/Car7/Car7_92.png",
                "img/common/Car7/Car7_93.png",
                "img/common/Car7/Car7_94.png",
                "img/common/Car7/Car7_95.png"
            ]
        },
        {
            "id": "car8",
            "image": "img/common/Car8.json",
            "frames": [
                "img/common/Car8/Car8_00.png",
                "img/common/Car8/Car8_01.png",
                "img/common/Car8/Car8_02.png",
                "img/common/Car8/Car8_03.png",
                "img/common/Car8/Car8_04.png",
                "img/common/Car8/Car8_05.png",
                "img/common/Car8/Car8_06.png",
                "img/common/Car8/Car8_07.png",
                "img/common/Car8/Car8_08.png",
                "img/common/Car8/Car8_09.png",
                "img/common/Car8/Car8_10.png",
                "img/common/Car8/Car8_11.png",
                "img/common/Car8/Car8_12.png",
                "img/common/Car8/Car8_13.png",
                "img/common/Car8/Car8_14.png",
                "img/common/Car8/Car8_15.png",
                "img/common/Car8/Car8_16.png",
                "img/common/Car8/Car8_17.png",
                "img/common/Car8/Car8_18.png",
                "img/common/Car8/Car8_19.png",
                "img/common/Car8/Car8_20.png",
                "img/common/Car8/Car8_21.png",
                "img/common/Car8/Car8_22.png",
                "img/common/Car8/Car8_23.png",
                "img/common/Car8/Car8_24.png",
                "img/common/Car8/Car8_25.png",
                "img/common/Car8/Car8_26.png",
                "img/common/Car8/Car8_27.png",
                "img/common/Car8/Car8_28.png",
                "img/common/Car8/Car8_29.png",
                "img/common/Car8/Car8_30.png",
                "img/common/Car8/Car8_31.png",
                "img/common/Car8/Car8_32.png",
                "img/common/Car8/Car8_33.png",
                "img/common/Car8/Car8_34.png",
                "img/common/Car8/Car8_35.png",
                "img/common/Car8/Car8_36.png",
                "img/common/Car8/Car8_37.png",
                "img/common/Car8/Car8_38.png",
                "img/common/Car8/Car8_39.png",
                "img/common/Car8/Car8_40.png",
                "img/common/Car8/Car8_41.png",
                "img/common/Car8/Car8_42.png",
                "img/common/Car8/Car8_43.png",
                "img/common/Car8/Car8_44.png",
                "img/common/Car8/Car8_45.png",
                "img/common/Car8/Car8_46.png",
                "img/common/Car8/Car8_47.png",
                "img/common/Car8/Car8_48.png",
                "img/common/Car8/Car8_49.png",
                "img/common/Car8/Car8_50.png",
                "img/common/Car8/Car8_51.png",
                "img/common/Car8/Car8_52.png",
                "img/common/Car8/Car8_53.png",
                "img/common/Car8/Car8_54.png",
                "img/common/Car8/Car8_55.png",
                "img/common/Car8/Car8_56.png",
                "img/common/Car8/Car8_57.png",
                "img/common/Car8/Car8_58.png",
                "img/common/Car8/Car8_59.png",
                "img/common/Car8/Car8_60.png",
                "img/common/Car8/Car8_61.png",
                "img/common/Car8/Car8_62.png",
                "img/common/Car8/Car8_63.png",
                "img/common/Car8/Car8_64.png",
                "img/common/Car8/Car8_65.png",
                "img/common/Car8/Car8_66.png",
                "img/common/Car8/Car8_67.png",
                "img/common/Car8/Car8_68.png",
                "img/common/Car8/Car8_69.png",
                "img/common/Car8/Car8_70.png",
                "img/common/Car8/Car8_71.png",
                "img/common/Car8/Car8_72.png",
                "img/common/Car8/Car8_73.png",
                "img/common/Car8/Car8_74.png",
                "img/common/Car8/Car8_75.png",
                "img/common/Car8/Car8_76.png",
                "img/common/Car8/Car8_77.png",
                "img/common/Car8/Car8_78.png",
                "img/common/Car8/Car8_79.png",
                "img/common/Car8/Car8_80.png",
                "img/common/Car8/Car8_81.png",
                "img/common/Car8/Car8_82.png",
                "img/common/Car8/Car8_83.png",
                "img/common/Car8/Car8_84.png",
                "img/common/Car8/Car8_85.png",
                "img/common/Car8/Car8_86.png",
                "img/common/Car8/Car8_87.png",
                "img/common/Car8/Car8_88.png",
                "img/common/Car8/Car8_89.png",
                "img/common/Car8/Car8_90.png",
                "img/common/Car8/Car8_91.png",
                "img/common/Car8/Car8_92.png",
                "img/common/Car8/Car8_93.png",
                "img/common/Car8/Car8_94.png",
                "img/common/Car8/Car8_95.png"
            ]
        },
        {
            "id": "car9",
            "image": "img/common/Car9.json",
            "frames": [
                "img/common/Car9/Car9_00.png",
                "img/common/Car9/Car9_01.png",
                "img/common/Car9/Car9_02.png",
                "img/common/Car9/Car9_03.png",
                "img/common/Car9/Car9_04.png",
                "img/common/Car9/Car9_05.png",
                "img/common/Car9/Car9_06.png",
                "img/common/Car9/Car9_07.png",
                "img/common/Car9/Car9_08.png",
                "img/common/Car9/Car9_09.png",
                "img/common/Car9/Car9_10.png",
                "img/common/Car9/Car9_11.png",
                "img/common/Car9/Car9_12.png",
                "img/common/Car9/Car9_13.png",
                "img/common/Car9/Car9_14.png",
                "img/common/Car9/Car9_15.png",
                "img/common/Car9/Car9_16.png",
                "img/common/Car9/Car9_17.png",
                "img/common/Car9/Car9_18.png",
                "img/common/Car9/Car9_19.png",
                "img/common/Car9/Car9_20.png",
                "img/common/Car9/Car9_21.png",
                "img/common/Car9/Car9_22.png",
                "img/common/Car9/Car9_23.png",
                "img/common/Car9/Car9_24.png",
                "img/common/Car9/Car9_25.png",
                "img/common/Car9/Car9_26.png",
                "img/common/Car9/Car9_27.png",
                "img/common/Car9/Car9_28.png",
                "img/common/Car9/Car9_29.png",
                "img/common/Car9/Car9_30.png",
                "img/common/Car9/Car9_31.png",
                "img/common/Car9/Car9_32.png",
                "img/common/Car9/Car9_33.png",
                "img/common/Car9/Car9_34.png",
                "img/common/Car9/Car9_35.png",
                "img/common/Car9/Car9_36.png",
                "img/common/Car9/Car9_37.png",
                "img/common/Car9/Car9_38.png",
                "img/common/Car9/Car9_39.png",
                "img/common/Car9/Car9_40.png",
                "img/common/Car9/Car9_41.png",
                "img/common/Car9/Car9_42.png",
                "img/common/Car9/Car9_43.png",
                "img/common/Car9/Car9_44.png",
                "img/common/Car9/Car9_45.png",
                "img/common/Car9/Car9_46.png",
                "img/common/Car9/Car9_47.png",
                "img/common/Car9/Car9_48.png",
                "img/common/Car9/Car9_49.png",
                "img/common/Car9/Car9_50.png",
                "img/common/Car9/Car9_51.png",
                "img/common/Car9/Car9_52.png",
                "img/common/Car9/Car9_53.png",
                "img/common/Car9/Car9_54.png",
                "img/common/Car9/Car9_55.png",
                "img/common/Car9/Car9_56.png",
                "img/common/Car9/Car9_57.png",
                "img/common/Car9/Car9_58.png",
                "img/common/Car9/Car9_59.png",
                "img/common/Car9/Car9_60.png",
                "img/common/Car9/Car9_61.png",
                "img/common/Car9/Car9_62.png",
                "img/common/Car9/Car9_63.png",
                "img/common/Car9/Car9_64.png",
                "img/common/Car9/Car9_65.png",
                "img/common/Car9/Car9_66.png",
                "img/common/Car9/Car9_67.png",
                "img/common/Car9/Car9_68.png",
                "img/common/Car9/Car9_69.png",
                "img/common/Car9/Car9_70.png",
                "img/common/Car9/Car9_71.png",
                "img/common/Car9/Car9_72.png",
                "img/common/Car9/Car9_73.png",
                "img/common/Car9/Car9_74.png",
                "img/common/Car9/Car9_75.png",
                "img/common/Car9/Car9_76.png",
                "img/common/Car9/Car9_77.png",
                "img/common/Car9/Car9_78.png",
                "img/common/Car9/Car9_79.png",
                "img/common/Car9/Car9_80.png",
                "img/common/Car9/Car9_81.png",
                "img/common/Car9/Car9_82.png",
                "img/common/Car9/Car9_83.png",
                "img/common/Car9/Car9_84.png",
                "img/common/Car9/Car9_85.png",
                "img/common/Car9/Car9_86.png",
                "img/common/Car9/Car9_87.png",
                "img/common/Car9/Car9_88.png",
                "img/common/Car9/Car9_89.png",
                "img/common/Car9/Car9_90.png",
                "img/common/Car9/Car9_91.png",
                "img/common/Car9/Car9_92.png",
                "img/common/Car9/Car9_93.png",
                "img/common/Car9/Car9_94.png",
                "img/common/Car9/Car9_95.png"
            ]
        },
        {
            "id": "car10",
            "image": "img/common/Car10.json",
            "frames": [
                "img/common/Car10/Car10_00.png",
                "img/common/Car10/Car10_01.png",
                "img/common/Car10/Car10_02.png",
                "img/common/Car10/Car10_03.png",
                "img/common/Car10/Car10_04.png",
                "img/common/Car10/Car10_05.png",
                "img/common/Car10/Car10_06.png",
                "img/common/Car10/Car10_07.png",
                "img/common/Car10/Car10_08.png",
                "img/common/Car10/Car10_09.png",
                "img/common/Car10/Car10_10.png",
                "img/common/Car10/Car10_11.png",
                "img/common/Car10/Car10_12.png",
                "img/common/Car10/Car10_13.png",
                "img/common/Car10/Car10_14.png",
                "img/common/Car10/Car10_15.png",
                "img/common/Car10/Car10_16.png",
                "img/common/Car10/Car10_17.png",
                "img/common/Car10/Car10_18.png",
                "img/common/Car10/Car10_19.png",
                "img/common/Car10/Car10_20.png",
                "img/common/Car10/Car10_21.png",
                "img/common/Car10/Car10_22.png",
                "img/common/Car10/Car10_23.png",
                "img/common/Car10/Car10_24.png",
                "img/common/Car10/Car10_25.png",
                "img/common/Car10/Car10_26.png",
                "img/common/Car10/Car10_27.png",
                "img/common/Car10/Car10_28.png",
                "img/common/Car10/Car10_29.png",
                "img/common/Car10/Car10_30.png",
                "img/common/Car10/Car10_31.png",
                "img/common/Car10/Car10_32.png",
                "img/common/Car10/Car10_33.png",
                "img/common/Car10/Car10_34.png",
                "img/common/Car10/Car10_35.png",
                "img/common/Car10/Car10_36.png",
                "img/common/Car10/Car10_37.png",
                "img/common/Car10/Car10_38.png",
                "img/common/Car10/Car10_39.png",
                "img/common/Car10/Car10_40.png",
                "img/common/Car10/Car10_41.png",
                "img/common/Car10/Car10_42.png",
                "img/common/Car10/Car10_43.png",
                "img/common/Car10/Car10_44.png",
                "img/common/Car10/Car10_45.png",
                "img/common/Car10/Car10_46.png",
                "img/common/Car10/Car10_47.png",
                "img/common/Car10/Car10_48.png",
                "img/common/Car10/Car10_49.png",
                "img/common/Car10/Car10_50.png",
                "img/common/Car10/Car10_51.png",
                "img/common/Car10/Car10_52.png",
                "img/common/Car10/Car10_53.png",
                "img/common/Car10/Car10_54.png",
                "img/common/Car10/Car10_55.png",
                "img/common/Car10/Car10_56.png",
                "img/common/Car10/Car10_57.png",
                "img/common/Car10/Car10_58.png",
                "img/common/Car10/Car10_59.png",
                "img/common/Car10/Car10_60.png",
                "img/common/Car10/Car10_61.png",
                "img/common/Car10/Car10_62.png",
                "img/common/Car10/Car10_63.png",
                "img/common/Car10/Car10_64.png",
                "img/common/Car10/Car10_65.png",
                "img/common/Car10/Car10_66.png",
                "img/common/Car10/Car10_67.png",
                "img/common/Car10/Car10_68.png",
                "img/common/Car10/Car10_69.png",
                "img/common/Car10/Car10_70.png",
                "img/common/Car10/Car10_71.png",
                "img/common/Car10/Car10_72.png",
                "img/common/Car10/Car10_73.png",
                "img/common/Car10/Car10_74.png",
                "img/common/Car10/Car10_75.png",
                "img/common/Car10/Car10_76.png",
                "img/common/Car10/Car10_77.png",
                "img/common/Car10/Car10_78.png",
                "img/common/Car10/Car10_79.png",
                "img/common/Car10/Car10_80.png",
                "img/common/Car10/Car10_81.png",
                "img/common/Car10/Car10_82.png",
                "img/common/Car10/Car10_83.png",
                "img/common/Car10/Car10_84.png",
                "img/common/Car10/Car10_85.png",
                "img/common/Car10/Car10_86.png",
                "img/common/Car10/Car10_87.png",
                "img/common/Car10/Car10_88.png",
                "img/common/Car10/Car10_89.png",
                "img/common/Car10/Car10_90.png",
                "img/common/Car10/Car10_91.png",
                "img/common/Car10/Car10_92.png",
                "img/common/Car10/Car10_93.png",
                "img/common/Car10/Car10_94.png",
                "img/common/Car10/Car10_95.png"
            ]
        },
        {
            "id": "car11",
            "image": "img/common/Car11.json",
            "frames": [
                "img/common/Car11/Car11_00.png",
                "img/common/Car11/Car11_01.png",
                "img/common/Car11/Car11_02.png",
                "img/common/Car11/Car11_03.png",
                "img/common/Car11/Car11_04.png",
                "img/common/Car11/Car11_05.png",
                "img/common/Car11/Car11_06.png",
                "img/common/Car11/Car11_07.png",
                "img/common/Car11/Car11_08.png",
                "img/common/Car11/Car11_09.png",
                "img/common/Car11/Car11_10.png",
                "img/common/Car11/Car11_11.png",
                "img/common/Car11/Car11_12.png",
                "img/common/Car11/Car11_13.png",
                "img/common/Car11/Car11_14.png",
                "img/common/Car11/Car11_15.png",
                "img/common/Car11/Car11_16.png",
                "img/common/Car11/Car11_17.png",
                "img/common/Car11/Car11_18.png",
                "img/common/Car11/Car11_19.png",
                "img/common/Car11/Car11_20.png",
                "img/common/Car11/Car11_21.png",
                "img/common/Car11/Car11_22.png",
                "img/common/Car11/Car11_23.png",
                "img/common/Car11/Car11_24.png",
                "img/common/Car11/Car11_25.png",
                "img/common/Car11/Car11_26.png",
                "img/common/Car11/Car11_27.png",
                "img/common/Car11/Car11_28.png",
                "img/common/Car11/Car11_29.png",
                "img/common/Car11/Car11_30.png",
                "img/common/Car11/Car11_31.png",
                "img/common/Car11/Car11_32.png",
                "img/common/Car11/Car11_33.png",
                "img/common/Car11/Car11_34.png",
                "img/common/Car11/Car11_35.png",
                "img/common/Car11/Car11_36.png",
                "img/common/Car11/Car11_37.png",
                "img/common/Car11/Car11_38.png",
                "img/common/Car11/Car11_39.png",
                "img/common/Car11/Car11_40.png",
                "img/common/Car11/Car11_41.png",
                "img/common/Car11/Car11_42.png",
                "img/common/Car11/Car11_43.png",
                "img/common/Car11/Car11_44.png",
                "img/common/Car11/Car11_45.png",
                "img/common/Car11/Car11_46.png",
                "img/common/Car11/Car11_47.png",
                "img/common/Car11/Car11_48.png",
                "img/common/Car11/Car11_49.png",
                "img/common/Car11/Car11_50.png",
                "img/common/Car11/Car11_51.png",
                "img/common/Car11/Car11_52.png",
                "img/common/Car11/Car11_53.png",
                "img/common/Car11/Car11_54.png",
                "img/common/Car11/Car11_55.png",
                "img/common/Car11/Car11_56.png",
                "img/common/Car11/Car11_57.png",
                "img/common/Car11/Car11_58.png",
                "img/common/Car11/Car11_59.png",
                "img/common/Car11/Car11_60.png",
                "img/common/Car11/Car11_61.png",
                "img/common/Car11/Car11_62.png",
                "img/common/Car11/Car11_63.png",
                "img/common/Car11/Car11_64.png",
                "img/common/Car11/Car11_65.png",
                "img/common/Car11/Car11_66.png",
                "img/common/Car11/Car11_67.png",
                "img/common/Car11/Car11_68.png",
                "img/common/Car11/Car11_69.png",
                "img/common/Car11/Car11_70.png",
                "img/common/Car11/Car11_71.png",
                "img/common/Car11/Car11_72.png",
                "img/common/Car11/Car11_73.png",
                "img/common/Car11/Car11_74.png",
                "img/common/Car11/Car11_75.png",
                "img/common/Car11/Car11_76.png",
                "img/common/Car11/Car11_77.png",
                "img/common/Car11/Car11_78.png",
                "img/common/Car11/Car11_79.png",
                "img/common/Car11/Car11_80.png",
                "img/common/Car11/Car11_81.png",
                "img/common/Car11/Car11_82.png",
                "img/common/Car11/Car11_83.png",
                "img/common/Car11/Car11_84.png",
                "img/common/Car11/Car11_85.png",
                "img/common/Car11/Car11_86.png",
                "img/common/Car11/Car11_87.png",
                "img/common/Car11/Car11_88.png",
                "img/common/Car11/Car11_89.png",
                "img/common/Car11/Car11_90.png",
                "img/common/Car11/Car11_91.png",
                "img/common/Car11/Car11_92.png",
                "img/common/Car11/Car11_93.png",
                "img/common/Car11/Car11_94.png",
                "img/common/Car11/Car11_95.png"
            ]
        },
        {
            "id": "bicycle1",
            "image": "img/rome/Bicycle1.json",
            "frames": [
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_00.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_01.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_02.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_03.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_04.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_05.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_06.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_07.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_08.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_09.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_10.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_11.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_12.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_13.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_14.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_15.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_16.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_17.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_18.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_19.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_20.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_21.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_22.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_23.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_24.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_25.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_26.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_27.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_28.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_29.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_30.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_31.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_32.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_33.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_34.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_35.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_36.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_37.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_38.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_39.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_40.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_41.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_42.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_43.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_44.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_45.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_46.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_47.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_48.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_49.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_50.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_51.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_52.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_53.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_54.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_55.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_56.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_57.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_58.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_59.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_60.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_61.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_62.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_63.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_64.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_65.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_66.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_67.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_68.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_69.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_70.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_71.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_72.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_73.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_74.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_75.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_76.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_77.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_78.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_79.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_80.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_81.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_82.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_83.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_84.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_85.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_86.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_87.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_88.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_89.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_90.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_91.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_92.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_93.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_94.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_95.png",
                "img/rome/Rome_Bicycle1/Rome_Bicycle1_96.png"
            ]
        },
        {
            "id": "bicycle2",
            "image": "img/rome/Bicycle2.json",
            "frames": [
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_00.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_01.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_02.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_03.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_04.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_05.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_06.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_07.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_08.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_09.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_10.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_11.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_12.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_13.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_14.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_15.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_16.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_17.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_18.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_19.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_20.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_21.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_22.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_23.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_24.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_25.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_26.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_27.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_28.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_29.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_30.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_31.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_32.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_33.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_34.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_35.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_36.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_37.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_38.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_39.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_40.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_41.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_42.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_43.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_44.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_45.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_46.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_47.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_48.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_49.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_50.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_51.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_52.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_53.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_54.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_55.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_56.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_57.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_58.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_59.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_60.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_61.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_62.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_63.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_64.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_65.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_66.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_67.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_68.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_69.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_70.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_71.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_72.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_73.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_74.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_75.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_76.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_77.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_78.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_79.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_80.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_81.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_82.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_83.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_84.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_85.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_86.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_87.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_88.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_89.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_90.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_91.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_92.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_93.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_94.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_95.png",
                "img/rome/Rome_Bicycle2/Rome_Bicycle2_96.png"
            ]
        },
        {
            "id": "bicycle3",
            "image": "img/rome/Bicycle3.json",
            "frames": [
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_00.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_01.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_02.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_03.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_04.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_05.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_06.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_07.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_08.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_09.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_10.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_11.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_12.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_13.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_14.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_15.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_16.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_17.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_18.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_19.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_20.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_21.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_22.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_23.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_24.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_25.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_26.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_27.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_28.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_29.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_30.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_31.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_32.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_33.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_34.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_35.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_36.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_37.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_38.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_39.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_40.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_41.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_42.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_43.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_44.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_45.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_46.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_47.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_48.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_49.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_50.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_51.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_52.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_53.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_54.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_55.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_56.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_57.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_58.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_59.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_60.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_61.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_62.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_63.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_64.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_65.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_66.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_67.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_68.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_69.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_70.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_71.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_72.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_73.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_74.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_75.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_76.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_77.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_78.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_79.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_80.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_81.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_82.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_83.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_84.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_85.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_86.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_87.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_88.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_89.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_90.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_91.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_92.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_93.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_94.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_95.png",
                "img/rome/Rome_Bicycle3/Rome_Bicycle3_96.png"
            ]
        },
        {
            "id": "vespa1",
            "image": "img/rome/Vespa1.json",
            "frames": [
                "img/rome/Rome_Vespa1/Rome_Vespa1_00.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_01.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_02.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_03.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_04.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_05.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_06.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_07.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_08.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_09.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_10.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_11.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_12.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_13.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_14.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_15.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_16.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_17.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_18.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_19.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_20.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_21.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_22.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_23.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_24.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_25.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_26.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_27.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_28.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_29.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_30.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_31.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_32.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_33.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_34.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_35.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_36.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_37.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_38.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_39.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_40.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_41.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_42.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_43.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_44.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_45.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_46.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_47.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_48.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_49.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_50.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_51.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_52.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_53.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_54.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_55.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_56.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_57.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_58.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_59.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_60.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_61.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_62.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_63.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_64.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_65.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_66.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_67.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_68.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_69.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_70.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_71.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_72.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_73.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_74.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_75.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_76.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_77.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_78.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_79.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_80.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_81.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_82.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_83.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_84.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_85.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_86.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_87.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_88.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_89.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_90.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_91.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_92.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_93.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_94.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_95.png",
                "img/rome/Rome_Vespa1/Rome_Vespa1_96.png"
            ]
        },
        {
            "id": "vespa2",
            "image": "img/rome/Vespa2.json",
            "frames": [
                "img/rome/Rome_Vespa2/Rome_Vespa2_00.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_01.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_02.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_03.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_04.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_05.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_06.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_07.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_08.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_09.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_10.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_11.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_12.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_13.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_14.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_15.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_16.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_17.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_18.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_19.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_20.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_21.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_22.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_23.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_24.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_25.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_26.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_27.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_28.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_29.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_30.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_31.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_32.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_33.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_34.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_35.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_36.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_37.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_38.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_39.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_40.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_41.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_42.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_43.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_44.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_45.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_46.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_47.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_48.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_49.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_50.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_51.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_52.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_53.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_54.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_55.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_56.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_57.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_58.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_59.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_60.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_61.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_62.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_63.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_64.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_65.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_66.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_67.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_68.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_69.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_70.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_71.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_72.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_73.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_74.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_75.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_76.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_77.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_78.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_79.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_80.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_81.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_82.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_83.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_84.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_85.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_86.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_87.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_88.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_89.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_90.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_91.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_92.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_93.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_94.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_95.png",
                "img/rome/Rome_Vespa2/Rome_Vespa2_96.png"
            ]
        },
        {
            "id": "vespa3",
            "image": "img/rome/Vespa3.json",
            "frames": [
                "img/rome/Rome_Vespa3/Rome_Vespa3_00.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_01.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_02.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_03.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_04.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_05.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_06.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_07.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_08.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_09.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_10.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_11.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_12.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_13.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_14.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_15.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_16.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_17.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_18.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_19.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_20.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_21.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_22.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_23.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_24.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_25.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_26.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_27.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_28.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_29.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_30.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_31.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_32.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_33.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_34.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_35.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_36.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_37.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_38.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_39.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_40.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_41.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_42.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_43.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_44.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_45.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_46.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_47.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_48.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_49.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_50.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_51.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_52.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_53.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_54.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_55.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_56.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_57.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_58.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_59.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_60.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_61.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_62.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_63.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_64.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_65.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_66.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_67.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_68.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_69.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_70.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_71.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_72.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_73.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_74.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_75.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_76.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_77.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_78.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_79.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_80.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_81.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_82.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_83.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_84.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_85.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_86.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_87.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_88.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_89.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_90.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_91.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_92.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_93.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_94.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_95.png",
                "img/rome/Rome_Vespa3/Rome_Vespa3_96.png"
            ]
        },
        {
            "id": "front",
            "image": "img/rome/rome-front.png",
            "position": [0, 0]
        },
        {
            "id": "cloud1",
            "image": "img/common/cloud01.png",
            "position": [-121, 408]
        },

        {
            "id": "cloud2",
            "image": "img/common/cloud02.png",
            "position": [31, 128]
        },

        {
            "id": "cloud3",
            "image": "img/common/cloud03.png",
            "position": [951, 159]
        },

        {
            "id": "cloud4",
            "image": "img/common/cloud04.png",
            "position": [1583, 124]
        },

        {
            "id": "cloud5",
            "image": "img/common/cloud05.png",
            "position": [1925, 214]
        },
    ],
    "hitAreas": [
        {
            "description": "Coliseum",
            "polygon": [
                284.760, 932.270,
                245.770, 965.360,
                249.310, 1083.510,
                241.040, 1115.420,
                267.040, 1173.310,
                316.660, 1207.580,
                342.660, 1215.850,
                419.460, 1233.580,
                513.990, 1237.120,
                617.970, 1231.210,
                686.500, 1217.030,
                693.590, 1228.850,
                828.290, 1178.040,
                903.910, 1123.690,
                933.450, 1085.880,
                948.810, 1029.160,
                938.180, 1007.890,
                940.540, 847.200,
                919.270, 804.660,
                872.010, 772.760,
                792.840, 745.580,
                708.950, 732.580,
                616.790, 734.950,
                571.890, 843.650,
                521.080, 859.010,
                517.530, 831.840,
                414.740, 848.380,
                290.670, 898.010,
                284.760, 932.270
            ]
        },
        {
            "description": "Piazza del Popolo",
            "polygon": [
                1550.360, 431.280,
                1386.810, 405.510,
                1361.050, 376.390,
                1365.530, 357.350,
                1373.370, 342.780,
                1415.940, 329.340,
                1503.310, 319.260,
                1553.720, 322.620,
                1567.170, 308.060,
                1586.210, 309.180,
                1589.570, 264.370,
                1614.210, 238.600,
                1655.660, 218.440,
                1670.230, 182.590,
                1674.710, 217.320,
                1692.630, 240.840,
                1720.630, 246.450,
                1729.600, 266.610,
                1732.960, 314.780,
                1738.560, 319.260,
                1729.600, 329.340,
                1791.210, 343.900,
                1830.410, 359.590,
                1837.140, 374.150,
                1836.020, 401.030,
                1710.550, 431.280,
                1632.140, 439.120,
                1550.360, 431.280
            ]
        }
    ],
    "config": {
        "cloud": {
            "speed": 100,
            "yMin": 0,
            "yMax": 300,
            "sceneWidth": sceneWidth,
            "speedVariance": 0.5
        },
        "road1": {
            "track": [
                { "x": -48.220, "y": 1019.100, "frame": 43, "scale": 1 },
                { "x": 96.450, "y": 1046.430, "frame": 32 },
                { "x": 155.920, "y": 1093.040, "frame": 29 },
                { "x": 234.680, "y": 1194.310, "frame": 34 },
                { "x": 345.590, "y": 1265.040, "frame": 41 },
                { "x": 427.570, "y": 1282.720, "frame": 49 },
                { "x": 602.780, "y": 1277.900, "frame": 52 },
                { "x": 707.260, "y": 1265.040, "frame": 55 },
                { "x": 805.320, "y": 1236.100, "frame": 61 },
                { "x": 909.800, "y": 1168.590, "frame": 66 },
                { "x": 969.270, "y": 1088.220, "frame": 70 },
                { "x": 978.920, "y": 1030.350, "frame": 75 },
                { "x": 957.080, "y": 975.650, "frame": 64 },
                { "x": 1169.770, "y": 768.030, "frame": 59, "scale": 1 },
                { "x": 1348.700, "y": 688.700, "frame": 70 },
                { "x": 1362.200, "y": 612.740, "frame": 64 },
                { "x": 1456.730, "y": 526.650, "frame": 65 },
                { "x": 1520.870, "y": 449.000, "frame": 10, "scale": 0.5 },
                { "x": 1460.100, "y": 470.950, "frame": 14 },
                { "x": 1407.770, "y": 506.390, "frame": 16 },
                { "x": 1352.070, "y": 557.030, "frame": 04 },
                { "x": 1279.490, "y": 567.160, "frame": 18 },
                { "x": 1230.540, "y": 631.300, "frame": 15, "scale": 1 },
                { "x": 1151.200, "y": 693.760, "frame": 06, "scale": 1 },
                { "x": 927.480, "y": 741.020, "frame": 79 },
                { "x": 896.940, "y": 710.480, "frame": 77 },
                { "x": 681.540, "y": 427.570, "frame": 96, "scale": 0.6 },
                { "x": -32.150, "y": 417.930 }
            ],
            "duration": 60,
            "cars": 22
        },
        "road2": {
            "track": [
                { "x": 2328.000, "y": 1348.000, "frame": 91 },
                { "x": 1687.980, "y": 1237.290, "frame": 10 },
                { "x": 1338.570, "y": 1384.140, "frame": 79 },
                { "x": 1128.000, "y": 1200.000, "frame": 77 },
                { "x": 967.340, "y": 994.250, "frame": 65 },
                { "x": 1153.120, "y": 808.470, "frame": 61 },
                { "x": 1365.810, "y": 689.310, "frame": 38 },
                { "x": 1568.130, "y": 769.720, "frame": 40 },
                { "x": 2328.000, "y": 1012.000 }
            ],
            "duration": 40,
            "cars": 16
        },
    }
};
